apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johnlbellamy/argoflow
    targetRevision: 123456789012/my-cluster.my-domain.com
    path: ./distribution
    kustomize:
      version: v4.4.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
