kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: memberlist
  namespace: metallb-system
  creationTimestamp: null
spec:
  template:
    metadata:
      name: memberlist
      namespace: metallb-system
      creationTimestamp: null
    data: null
  encryptedData:
    secretkey: AgCs+7gKDmCyikyNtJhduodmLa+QFOsEttVfTmhQ5fHhZbif6pcLMwHCo6PtLXZVfQSthGCk2hDR7KZDCCOTNtxZfCFlIY6smP+4N+f2eGq94Y9zLzZEAV7H+btE74s+D6NuKeYTkHGC0NW7iKSvnGinYj7L7UUf2HXSxhM1LiHm7wT76Xv7lm7lqoO/8OMrX1TOnmeFCYYVN2nBV3z7CGBjWR2s0c6CAB/grXo710mkPWR8Va4et30Qis5ekVyTMrxJPZGFK60MIdgdscUBSW/WFPTgUjF2aPxesdxavVbEozebcCW1OcLqqHnsMsPQTM0SI4cNq/GtEcQUyKwR0h77d1fSQ8xRB+wDU1fBB7F3aAKuPXLi66WOySiwmemAgCQVuJkeRkcQDt9UQaJvyDv8hb+f1y6jckepGMIYX+LIbn73kD1maIAJYlSdpxQ8vfhOMZwh++DJTFuwGTayEmDcIbW6WRlvX2Hf5HqN2gssMhYMfLQEnItWfnXqzqMJAHUUKRBngUdaSxf4xZ6zsvHA6hexnolcSZbWAdjKdJRcom0eoG0z9xlC8ZdN0NghDyhzEl3OeIW1Xs80Fe6Bb098a97+38v45RgkH2CYGiXmird6sZnZop5kYiEeR8zj9wRxTc5hA4W7UdLk4ybQQApXz8CkPO0eDRurHX7EcNMHlCc4yXNT1+1M6UEuMjOh8dPtyipu1/cUMaWKY/eQUEYaLWHer6sB9qh9YjmYyVELnd47Jb08UxWUBEWkLr0vmNn0TpCjp/18KJYBL64dw+tdhk2eMu9Atb+wcM4RgbwiQ6YDM5XsAOgLfJrMbeymoH4Sq3Sl0/HmUO/6OK8PT6ogwRsz+MUfWKn1p5DajhQIncy9ULfe0E4AWyzDIj6Epb9ChXwBDwDJK77n2nnKwmtkuDs+JxqbZGEizhkiHbc=
