apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.mycompany.com/argoflow-aws-initialised.git
    targetRevision: 123456789012/my-cluster.my-domain.com
    path: distribution/cert-manager/base
    kustomize:
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
