apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvcviewer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.mycompany.com/argoflow-aws-initialised.git
    targetRevision: 123456789012/my-cluster.my-domain.com
    path: distribution/kubeflow/notebooks/experimental-pvcviewer-controller
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
