kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBuZDTd6PJ8KtpIMyW48+Fl81q0JvKOl83pxZ//N1hGz+GlrTZJzaGJuL9AwouH1wKUyam5nffk+1349SS8wKSgm2Hv0a3cNqdSDrsEfnGn2ep6G8dO6u5njIUo3hI+3hsKD5JNIjeKVy3KMRAoiX+HL6QZHb/EIq7+fsfeiyRR7bkGS1uKpv74LYAg1/oBuhkTw/fc92NmhzGLlWdylU0tuyh4crB3yapfuye9JjKg2M5BWQcyfcKYKPnSCjCXdAJDLCg4VuZA+6DkMZ6EKwApsUubXZD/61qa+Lh1556JwCi2alzbw/HtxdiLHdFCRSxfcvRPoXVXWSlcCU0LTEpHAROv4KDyrug6GEcEXgfGQdflsMU9AVaNqTMH3ZCxhlo4QPKAiOJ1wNXnidb7uRKbEDhTbSMiQJAEJN26QuE4RuDbJYOdpZ7qVwO5+dwpaTTg9c5yDw3dBcEKS8bABdAnkMmh3B624RFSTDcQqYeK1Bpwi5FTUaMQ47Z08E28DVFBbtCvQIO/hUt0V1IiUDx2/Ld76U7IM8YA/RDN4zHN1cph4uLmfxhK210bvsmwUqG86+Frc08tuUc8bcOWlOjpG8qkL7APj3GF9WW6tMwknQbbbfflaV03aZhBHvT3hX/wudChQDxzvH3IfYC12OwMVHKA6bVXO23jJEb8p5es/I4od2ubKOU7cXQtYdoonjLH773dWyIl1c/EhhhMgkL3VHBzfTDrbx0go8Aliw2cuQ==
    postgresql-postgres-password: AgAzTgjGmzhacPS89SeYwZRwbMS5BOm8Crj+qSAb9aDGjNHACSghagKywl8ETs3ih05Sc5R2m6Ej1RqjAu5g+D7Q/dohxjnoJ2y9FYN/tg7qmU1S7mfWFmAqybfft5ANjGU082fNiaEaQkxNOHshT0DLRc1l6osfyt2zX8Q6kVdgR2whscUiV/l2agCNVVxxieQAl0zsduMi96Dmz6PhquRJNz7SiQs94zPhDde2xiQ2RkUjzbj4p0abzMlhni+ZlRn+7OrtedXOIpAmQ1UrQE1RX8vsahJkHnH3sli9UxJ4j6Ts8S329Ep06lPwvZLweZqtTPPRBL0HEJqr0pMwkSm+Wre/mR+AgqarFGAS6REaILAVjFtP8vzEfSRtbU2EOziaZ60sot/JQP+xFnS2pXcZpDKyTzUFxH4WRVuGZRBsSonQAmTtsx396feeXlUwsyXTfJjZp6quszoFpt4MbJeGEw1vCcc5gu71eXAO64z3DMP4cHot+zLMKGU1CjIZ3jpCqtcoOsGARK2icfijQC50L+bNslVmmUBiwIIiiCYbHDXHIZ/TAAWPfr62SyRotS/50nXhqFsJp+KY2WR72I1GTShT3ob43xNOdT4oA2ENhF7/ZNDjbdY5p1alAHo5dvQkCn+9O2atP5wk++OYsyh5s9HPHmhSurN4acaMxPCyweeCokXXYkeOSM2PIX21C8WHtoW5l6ZlzB4Qz2FPmZRJ1sMKrGOPhPNKOoS1a4gtnw==
