kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgC5lgHykJtPkymI+95PvcnOB0a4crlLwdLYqe6IVZGttpZaDi0J2LfIry6wHuieHvfAg8iJVn/58fu4Qi/6fINxT3bTtbFidIM3OpGhuSwaGxwU0p3EZlMuAW+Yh827mFDPZIGtAx7BZDgpUlVB6hnW5m4zuPSfRLVbcAo5VDun+jQECVrKt/hW6C9QQ5upT0aVXStITWo/zbWrye4oIRqoazw8pJFrADy71CLI65EdNUkWucGIwMtfXH6D+l/5SB7i2Xg6Y9m9LdLBLe1ULH+F+CxVjElYjknRz7bDMTGF+gs2QOgbZK7f977bT3Bf3JAwM0m+vBykwuN/t6MOyKzSpjP7MpJbWRLcIjwupkV2dK0na4ZpguawNlPFXWHd5enGthvVDycoW1UnlPIkUZKERrtf3htnTE8nzuQUnv4iE/hCLIfjgCNqwiE1jLO4UInJoFWUEaAtR1i969U9/YEziPaT0X2dVUD5nleHwggWexcz3XUx6Hr84WQe7aAxajGEo358Wzn0jmQgwpyng/u0/GFMgqhonLoibH6SdzbIOY76VTAl2JT4nmV7ag5vrTvVL5qWSlxwb/UCj/X3ybEx7Gg2RA6TOa4C7Ri83gzpRfD2ayENAClYe8ZNjm3tLLQJoc2NtybekLETVluarxILb1g73x8SyItTN2q2mNMBIaNe+4j33e9IR2+DRkJoxha1PYzDTAW50V4M3yoYJtZxuDxsxqnKzNt2pkkrNhedXA==
    postgresql-postgres-password: AgAr91il6lOkxB6e8KcX/6sbW4V7Axy6myHW/pkeLfoPgGu0dCDIhg8sYIijZUVpjSWMBoD87PVTQyOyLhdtxV/bBLFunURR0fJS3st2vArzNWAr0mFwAOnmmJlIfwPTxAYDIxGpjJO4e2YQVSTSJzs6lk6B/rm5TJPZM/VHqDKmOWKHMx3ByfhxxW6EtBkRsQ+qVJzNV3adSDDfTTWcTSwAcTuV2xNkdNlcCm+7MzCRckcXKE0wvAfUYFtgwPqUJCMy+moH6e/NRfGz28k8r7fZJQBKEfFpAQ2n5MNcvfc76glfSMWsiH+fRNSt+X/DMb3H7q2skUDTl5z7TfEgKpVP0Cw1Be0nab82ZkpA2N4D1Q/lZRM+GWDQbnfUl4JE4f8QZVukyxnxnC6D8Fxi+dbw6hqqv7tiwKNBxP0gRUNhYmYKBkFnM8xv8lxTRb0D3lpSCmwynQuOah3u9YozI1/vL/wB7rmCGDiLgMdT0V4kOrHl9C6aKIKbFvqbT+xGgtxxPPOzDkS/GU/J7G38l77KFnuPZXaFbBSuHn6ad8bv1KPkTBBNlkiLfvEEEdJvlOEGLA5d+fB6Cj2cWpai/nbW1rpr77JZWWZWCO0o/SK+wEb4dEjiTUx1pXLn6p1oBP3AwxzwTLKxuok7XQxvnBoFW96gGoO9l5T5GJ4yhvB7p4bPzeGmw4hZ5YnPwxlOIXXUMUm0IjD9cczE5+sy0/J71XfJ6M3+XDXoXZT+6HbUdw==
