kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBcQd7ukVseRXfhxETqF4OkdYmbQONBvEG25mjEUkzQL6G0jh91MkDQK/d1HdI7KTqZnR1GzekhBeWRfbDEe1mfebtlyifj8oJA2JqIkf0fD9a3XL6iVo3PiI3c05tZo8+BZehRB0JqSJz83dc0yjfk3IW27XKUJoEgTtV2idFT6NWKXK98zqP9SP+RPWEqcS7jYeVmrMeYly9jYAi1gs1L+fKQ7hRQnuGalMhFRVOUYlkHjWssMGRMvOeWaZ6lyX/3yaemQfpLGUU64tVFGfFQNeFBNXpkXLTK/44MG+MxMjoyLM18L5ZfKJuhrS82+l8ef0lFr/Fj0Uj+mf46ol8e84jcktanhfEzu7EhsVZs3lFRngDhhwHw5FzGGklpinDrzR5GdobErmANJG0Kkp5x4fJU67DgHX75HLsdZ4qEifQiCNoHthTGpDmhsds0BjumSdo7XzuBMehNGUuGCYwxrUGdaeSJ1rRtrlmNHZARB9GR5TvHkXDS9ASMX2Rbx2HQP0lVrvukRGl8OwqgCLqA1r8yHyzxWqsyVUsQXTyFZJZ3TptrBuw8T+D1DOhv5zwPStQ/I2NwCOKxFc075mgUoOnn1sTqM1Ygu3HydHZFNZxr1XY/G6F88HCFEY48ZtKyAE0XB3C0xcCk6jTv8IdqWZ6FZzdWBA4TbcrIkxGxaH3SH7h/W+6yZlbsJuyh3rFgEtwYXKx+niJ+uD+EEXgdyPE13YPOo55udeAAbtGvJg==
    postgresql-postgres-password: AgBYEk19bKfFn7zjvKAySDywUnjvhFYgv96MlJkXonHyHUPcxzDufMzzT+W/uE06NrWNNiiekFUSsDll+UNNAy7dvoibLOObp3/cbAd/Sla+yuLi+XGn2hnQHgYb5E5IvjyhJPljLJutNePkHYj1bs0AO0kHmWcQ2TsDUy9kho007SljoK6B9Jbz6mCNiF3I675gcEAsOpmRxPaSrTJ7Xz6ESM0O04dk0tsWD6t9X+tjEo/eiXH58fwbqDNSKQ9lCcYN0W56bV+7/TI4Zm3jOIdbQlmEUldTv8mJyfHbY8oD4V5g5CdnaVHwSliFruHqj0gM3JEe6iXQzxkqOS28BsL23EAIcFXrT6b74UmZSkUYMTXBaI2iPVFueu7eIBJSbRJ2RHX76fjSb2nRh2/8IUEpO7QSTrMBjyyN43578zX+iYNgGjCQWLWHVlUN8oJQb/sylmZaT0501JHmWDhQYoOPMs+9+3LDxw/E4C8sdRziNDI8S3ebFhNqHRQ6oKpvaNjLCHlQ4e2MJ0U12lqdcnoKoQ60LraIHfpZmcoHAHecQPADU8MtbH2d3+zl6qniKGZ29YHFqQQLwm5F5rvTtFwlan0QXXdh6atze9ublLV4bHU/agS54NMr9JTC9q1LX4zHurzK6991RfVHZFRP6TlsS2zfCFq61CY0r1CdfYKBIHQcVUIBlZ7B0WhxbOPsPKF2b+Kv0DlX7hmpYFW2VdzrYmruWJUNP+BoCTtZap9fTA==
