kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBTrua8ezwAM1WcwN1mOVh7me5dguZwZP96mUZi7809xT4xBEztQBKc1HFoEdNlq4iOGBj0bgMTIrC/fyN9oM9FkFUTG6o/k5yGSD5F4SgKgrDXTkfcNmp/DxS8asnU0SxL2wXzUUALx2EXDliwvFa5D7u62dGnFNg3P+JeDX8WiB9Wfz7fHg+ejafu20H4Aj+uVp+AAm9CM7b3GpSqw1ZxUEeF6BY7+6DGhr0wC37gvQO7KEHZYR3q2ILwvnzqasq7CHwz8Q0u/sMS0v6LADVofaChm+Rg4MEYE5mzY+S/JlM84/Ymy6jLBAKrV74H4v8Duy8oISp7vF4pfacgMIVYE+giSl1cmtvYrdjmIzSn6p8i+lmSx7nWV5amM/rWZiflQJydkYhBGsvUOamJEExD4SONRh7j/l+2IlcPZUegS7RyQc7A1rNQsE6UB1iijSeJW+xC1/SWnJvqThk8a50i3WkKLzi7H5xDsa1sjXQhtLgcwFqXXcwqg60zGATLem4vmDJcVL/+JQnF/5dpKAcVHAPOD1sfFNWJ/T4XxnqUaeb40CwOKOQHpHLc6ddePj2NNuCY1t+Vt1HR/1khs/2SNhY9EOjXpENd1pZseZ+IFf69KhHLg0hWAInPpEQWKtROFuLT434VpTSsU0xPVqI3QFr3vxZDtcOnrOPXAOE+7yClzP2NlTCHIo5XejWppYG80Pg2E+161IpoOSKgogzT6p4nbmwnQODyAsrq6QRt9Q==
    postgresql-postgres-password: AgCav4WJxswy9rCJh+Nu0TKqt1Or1YbI859kDAKveVhmDk8tU09jDf0vOU50PyGpcVVUxEuu2zkzDITOF9SjF5UmOH/FB4x9qU/cRou6wiZ2tFMoVeJl6pLT6EcN8fPk8BcF3ZCQiKaf4xwQbiry3ZDdNwtQgYzqhB3hYIb/4Jw3s/8UpUKQbJ/9sph6GUGHbtd0ixb5tt1FWyzwe78byozV3i4bH5ge/kyMdDHyTmN+HOhQwIhNkXQuHn8O2fhrrMSR/yDkkTDx19zkt3LOlV74aDgnC6QE953i/3TM1XDBhFl57HpiieojJz5bX0bopbXjEhKIM2JDFmhuvJzapAwyrfhRh0DiaVLtONECUHP9EoteWY86gSsiuuts/gTFEzSV063nyEK4MgA7wPjKAWXpTE7R2wGhoaliLynJsC/J6kOy6G4QWM6/I2pWUbaCdPd9gCzdkntioCrlD4sI6c3u62/0CPLEpyY+vkZ2gVzzGqzqffGhrEBM0Vc53X2xgjoKbHkvtuhEJGTSr3zMr/IccU8L6qWnxRUnLjaqpcQWeuGvKvRZ7yKqmvG6SWwI+UOs6JQ+bv1W+tBTbvqeRqvncAl6rL7xiZo0NGpGqPEAbJ68beWKQWbns8nBDMFQ4WEZI8QdvB3YNecWz7fhbLKFntet4nQV0WBrl7fDm7lPK9TNRg8r2H/Dgq/o1hnOBU34DkE8Io1xIB9JssfUiOjCmCJ/uhKKIZura8uFFFi52g==
