kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgAX6fdiEEfUr+L7p/fh6C8u7uCmEXaON8sxCDPMQKWPpFw17otfG2s+YNmxyl/GY28oIAP801IeeKktIEXM1MoF2llkYnMcqx6EP5vMIEcayPkChXUCJJT3/CGyi8yAn0il+E39U73AEAlz3RAd4hyM7JoNHnBu7tdhF8C6nUE/Q7u+c2xaXFsEJRuPrEsxZ08y1aVWbE4JFN8u4kf4hgopdGDHLXD/XhCUgHGv6TdyalUjPZG+ftwOqB3QCA1uRJsXrWJKWr9fWP4q/d3jw7jCJvGFZ4hWlq0vKuraxWlzyMtBWCzyjQyoEcIsud1OA+ntJ+JyxEX9beuNniwyW5rAEM0vg7IaxyUHH34krEev4Fuu5Yp5kj6UrGFUbKXshtQd3uGSWE6M8XPwrUkNa0VYGmdDYGzuGsrRVnDmjb/u1PfXujiuclaAHuDIJ99Uj9vocfQqt0g8syE8Ppts5EuETz8BFHkGAa2W3PwAkuR/b6hCVWw2mBqSXT07Fvk8WW/398PWsAhvShX1bKZnlL3Yh/X63yZlozD/vPdno/pkKIkiCb9/ik9+5E9k6E+w6Tqf4FRV8uXbYwI5wzd/41C008HQ8IfKD0QoC5MHTblrLCBm2G5wMKetMD0dMEcDEXp1cJ5GEw5nZjc76NKqaI0vMShCx8wM1aqJl1BRR+mFnIz9hNFicUNGXBCKNbUTGMvEYKM8Gr5FVRBxZIgLWGua+l0OiR5oddw/BpQAdqYTTg==
    postgresql-postgres-password: AgCuDM6MrfdACqMV8yJF1HPD73oSXEZZZeO8zHrxgbQTOdnN4LLgfy+NnUYcNMs9cU3WE0D0LoioaMQ8r0zDHBq/BVAxn30CurH6T0z5hovjYvX8HFYGiMd72wMJmcbVJC/W23TsRe9Xewar3DBZSAO4PfbhH7Y2GqAnpSnumprukZlbrZyCFm7bq07WSPaExDrSl60h8KfPhJ2oyqyZd0ATzAx1DYVIjPuIr3ZHSvbKKW6EX/irCr2igZIffdLrAjdYXh1x8ISRuYYU1FxAB9im6bff9N5P4yQslDX3ndLC3ICW4a45mktcvVzGIlc5pkKn2G3fVoeCuxo3q+Mt2prOBppazK5MyEaycVEEO9/nChhMJlrAmS/MHzlsHv/WxMpvJYSdfv1UuF7uSgwyXnDtyluqk6oyAFjtpy9XE0v/c81QszZfyMtgHUEYza7YOytYp5MkP287eML//yziiC2+vE1Lcr1Z6QcDIZgeXqeb1JSGwNehPjLt5UxjVGicf+f4PAbybyiavEEo2UW64TpZFayr9yLSl8n8ibEgThxksP5weqg7zq+xgFox86GDBUvGusiV8FWrdjl0urrHnc1M+P22AVTplvhtf1easxam1BgQla5WqFU9vYymQP+zMQKC4AoLXCn2KQAa1F/yc1eooY4jMqh5duCQkg1lRYbFWtNBknBX46dzrBnIM1E4bvz8vcnG8mF4xo+51PuFLvgVB7bU8QPP3qvCh3RpZdSThg==
