kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgAXjK0mprbPN8dYnoel9vMgjA7BPAjoauuo2Y8l18vPS/nC2MabZKXViiR2IFnhb4qPR0qDQ9U3U3L//IFkhSDoXJ0DtZ+heMgNsrR9AO9n4//0xQfxpKOctus2OgecuGGhVbLdKSIO82o8BUxsQleZG1lVsJUUMgZ0ALxkOvEmsB8Dm9uCQ8WroK2i1EjTYz0UUMAK/hF9JJkl61eYRAs2NE7nRp1We3WJFLybr7W8d2OiBZ8vVyxrNPk0c3Cgxez/1OiQ+VHIINSiSqlA9IBMXxqdDCCpZ1FjtR23tDXggofVwLiv9FnxM4dHVtolrMMRUsa5JpNjCe+uQiWXX+kVQwfoRXeBMuyc6BUkJqperunGrHny0rv1s+y8tlTR24WPN1XkWznXN6ia82EeEiQR9XOTHNVKl9VOLSfTRdsvKtqcTQD1Q6elqjkyd+V8nHNQQxYRZsVtZRwgejbjqoDHpRhOtp+wW+qwpCbv85ViH3oJROqGhfMxfXbojhjkk0Yztnrymu3hn/tD7tsAkLhuII1MY1lAxJIWX8OQf1K/VmKmLqZjPeWueZmeN/Oqesaa/PUVY6ODu7Cf1gV/Sfp18VuJbBAFXUX7xnsn59CIBQiIoWkUdrEVwS2EMD149/6p/SR/rfIft1D7YcKx3MIn+ZkZDxrbRRzUe5JTBJR+6+haFqnFbcG0jAsvVX9nv9wMgl9Dc68dK1ByZo5K+BdEh1EQ5KHrnk7xRDEjnFoIpg==
    postgresql-postgres-password: AgBtI+njS9fvDgECvOo8f7vGmIgGH9+GpT+ANprzL4lsDmX6XQb3qDfSbbz98gsA1I2EbFNgK5qrAg9h5aVzJCQJKX6F00cTE6SS17SQ/iTh6Pk3tzunDONAOKAmpYL60L4r/FEQL6Cc+mxnCtxRHpQnxMvinud25FiuIBZZRNznVItiQVveWAfEysGjnF4fCyL2kjXnuLgy8hLFz+0Oz1FHymlDvGX/ytKN0SDBDv9uerblJoD9LoTwGo6c3We9JBkYB5GEUpeTaS+RwnXmUuOrrNG+8DGHb1il/oHx6KSx/JC6/dkxz1Esm2ftTHjWxLJP5S63UNlNLfydDAnV1U3wOmQOeX9SqPusKIE1kSBc/Ht6YFBv/QqYp+wCwUo7bYK+rwRBK9rL92+5WgWt/O0lf1RcVgASXoS28BZMM9KrTfpm36CN2hLAactYoNFzIYM/aQ5NgN1WT8ezXyPk+pT2NF0vCOOWRbQ/GLZCqV5TnK0rSe8cd8fbPC9RQuYxa2x4LqFydLEufITBJaI7Zuho+pfnor6URS6lhQ5RPr1ASgUjHhqdreEQmYhYI5O36dcQ+01ddbNWD6/XJZrKKs8oLxvWlgCqJUpbkk68+8/jc2D2HhYowi4jl8Sfqb1B1m+TxsTPXnheY+xnYSNx6kjxYzaFNmhTXI3ZUWkSKK5ieOrJxaYchnlgUd/dPfcI0C9DrUx80owpI6GwRdCFvuY5r6daIUnQIn718eMn5+v6MQ==
