kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCykHdJsw394A/eRlVnlicvLXh9JrKQAdn5QXfgvV+7+qAQcLs7aWUPZtgPdbP3ZEgHbO8vLJveu4+duNPz2wnG9MlECOh8nDcnauOElrHtqZoigJtozkp5CxU8lBgFWskEenzzQzOstkSE+XSt0yywCcZPgjdi04qnMKh+yZT7wZKeB6DusZQNYiArEHJWKhWLuz764Mpjck12Z9LKYN2CI/2HXmD6M0Ly35PgdKps3KNcMeZpDtduw29ID9DwdOoTIXaZLqQ4SFTl0fywIrL/sVyOg/B1uEJR1JzytInIoIZvHIn1Q5xawXpof/iA5RD3XilLConinNJpQzLxLHOI9l68hz6fw4zquv/9wldnkPCOxRickmt0zAlfU6LNzVZB4OE1jon6kkU4MyKKAjOjsstLm3ngpP92MXSDiSmoYlJ4mNEW0/C7SBfSxwYx58IjMwUVEEx+ats7LsrLmFTbn//Igq+iccsXWOA9v5PVuM7KS6WVEzei0KB0Yj7gpiJLwOuHix7bXqdHgj3zeMgDRryW6/+WqHjogeCS88yg3GHScfoWj1P4Gisee8CiWCetmHKD1D8X821h7xgZqk1nZ/Y6m58/ZGNny3H1bS0DaO73lQ3GjV7jqmpL1JILeFmZGKyCJzZGDlb4Gli/F1v6+G/P9g5OwIPQYJtrHpFq4BYe7SHiyA+B21XiBLYZu1i4qYdR291S6zdQmJ4/XDLR9q7Ebk6VqEoij+9MVpKhHw==
    postgresql-postgres-password: AgBCogo8CxK9NnNcnK23VENcLyYoAsy/FnJwd7gikxYutKcVjPipVA3x7XqzIxpRX2feLJKEmvdM+Bp4ZjIx+KgrbF4H8sg5GVakStCel9HWZ/vwrqAduEu5D/DpyQEyd1D5JyLqBGAoViZU9V4ipz8KGv08dnFzR2THRZNI21iKybPPxgJdU9z/Sks+7hfpnrdpvAZTWBgTdUFgtiNypntWCxLaCkeueK4wCeayXWm4PMau7ASGaLiQIVcBDqljZJR1lyQ8IohbivlPnQsMBsm3Llz93n1XejeR0RxSiyNes5lC4G4ikGuGwqJNJrRvUboBTx9cXE3+zzd3ipQ2g9BTl2HCX6DZdGzB7CeB8xz/0XX+FtYD1jqpHj+zlWkV6QiP3wJNLeydEZ5ef2zC3RTGIQPJHYX5bX65Qt7qF7y3Fw1CS5Tg2nYSQp+DrtK48m8hmpgd3Dz6r18LTS68pyf6J+VN1COMhN7yMnAEWNG9CU0W+iyRZdLbGygiafQSJNE7pu/ZYSIdmPrLFiKc0mzNNm7QPG8KT/QfdIfQSFGMBuyICvTNUU5BOm8W/pvWrbpOIZWh1elgud0dl5eIPuRUQHvqUhmBamVIFVRJkMzMglFgao2BktdXCkiHDkNcr7SQXEtROLOnS3AC8ob8nQ3b7cveKViZswiSQHnJ5ecf2Trk6Gt04WvvFFoDWgr12SMjSJMmePIVxUvfqC1P+QfzpJ2TrD1sAmfo5G1h9t06yg==
