kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBC8GHa+hYFz7GLKQnZegrOhpVZRS3F8PkVFO4KKMukVi3kH4PKOkB7VR6aCsNvdFLxmQQRINpXf33lL7orxEopCs37IfzekrmTf6hK5ycxDaThTyfH67bpKUBukwjmpGVlqycwy/uzXDOzhktQZp6WqsIuptteJ5NhkEYsTEFWtS7BxaCd7tE8UAOLqoACen5sjDpjLCFchX134zFEXtXhbARLQNM8wp1iNFPZ4av4rVfZdK3fKQCLHU/2Lv96J9hxWTeakCtkX1FsldOxPPhf3V9h3ZQacQM6c2NbahjKBC3d0kKLAszxmjQQheZ8VkNedajw2H6SVDg/r3S/bpf+xGjvMpvez1l+MtPiGqrR07HMIeT5AW+n4gYAK+GkfuNtQ4AJtlXMWBSurOSQJ5vbPZjftNKE4YIlQWJtd01M6FP4/q84hBjc93aelW72JFxGUpvp1iSwl74UCqwCksSJqgc2JIOGnK4/nLDKUx7fDSxq8idzAgDyqVhA1tmd46HrG6ZUOXfM/1NNP2rGULL42m9PQgv2d2NrhI58B93iXsAgWVTmXAYdpRHpMWbyurt7gVBdasB7gyID1YsxAEsJVi0VW38z1vxDs3I1I8/2GOdPEFPQliU5Z4o1Sg7tgmsI6o/e2Yj5Fg5BjMoyTgqAGTcEi5I/SKRg3fT7x8j8lCoAtzJDwzU4/dkRETRlzKY8gk5ZnuFMDABkC1OoYacgaFjwEeTIqzatmkLaDEMqww==
    postgresql-postgres-password: AgB+/424ip/nW6j8IE57JrMujpDUkphRhtDNqW/hDSfyby+0g22nUJ3C3gKJ+fottWiwcoAd9p9V0m/OsoywxGdGSXHN3c8Bsz1O4Kp9nyoQk3KLjyyQtxOIQNv12o73lFKbbhJPN6WCUJ1WapYpnDlWH68ZDC14oCkR1A+STya6fgrHNjMGX3WAiMfCeIrYOaeFyUoOhPLeaWGkwB2uMjV/7qa1gedgNvNOdTvqE6MbjSSHRd0hTNgj8Stg04SbNTVOOAAdU6Wp9FGpmpqirxQJTwByDBWpNtKbdsrJPs37WF6JKeyX4V55j0yaf1RToLURddpw/jeFdvktyIg9nQfUI0OXVwc+nL5s9pn/mp2HNMy1T2k8lm7S8IoelKszgUNHbfGgvnHJaSNWlzahM8t7Pd7qr4jmRvirYGsPxVZlUmdFKokBENb1ol/YJoW7QrI7dLc77u2CsP++LHufgvUOvK/HBgH5go5HjrKbSGLBCCA6VLE89FeAT+H3BusQ0NOcNqoAZ/HjZxj00jjafc4FRuEgIUjl2CA4n3CwJKXRoGD06tx155DNgoJp8l7m+lpr7ERWB7B8ABITO5CG5N7wOeUhUruTXWPcKPgObJGfcxqu5eoMK22kDfErVx1p83E++vQjX5/oWljD8VusGtz2Drt9JBbOZMgwp0xBnOyM061RxYNuiXpcI5gbmWR6jOFe9ZLgAklgWFs2d2tb7HGPOuVkkBtzH91yPhV4wbEJ5A==
