kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgACm+2myDo2YD1No7HEHab6bNseGfXChlNixuMyGLyh1OxBY/8az1qwmLWsMW0ZqU/RiySoaXyadW6qrR5uXAjCxunG/pnkogBJn5vgtWhL7iCZPfuZe7HRXQx7rU6zknKJL1pev6Oe9yIZZi0JnGWWiwB2aCLv0RTH8a6a/ScHR10YULMMC7Le0FfJsgOZKwgz6CMwUW0eUHVQnfLrCEQP+jinW8Z8fQfHgz4VONDWtJhLN5P1tAB/KRxy99G2+obtQAy8xq1DRtBd538EW/4YtuuzM7MqYi8rkh7pZrKDVn6cAZpP4xJfsaOK20KdlUJyOPrlLsdNRjNk/DaVgKoibIYfpGT1Orsoh9C+OcPiGIYuiDG4oGEGVJ0mryY4VkuphA2YbxLHS7bC15kxuCOwYjzWF3suHpeVMC/QDOueCwB31KkgcpEt1D5NRn2WEIeCN/Pnsz/EP8HV/9xuSmdiFIa9anNd456F8H2ishgd6oUZ5uC0SbeLTwlCipMa1phqR/Zaao5V/msOQogPgogQEG3s7zHRsAPl9yC+nsrofw3Ztrhsabp9YKEK1/SB6KGZNdpEBA8izNWcOlykm9iFyaoxLmM9JxMd5ZJdZvcl/Jrq1IvYgiNz/HC2dZqfAX57GnwiWr5gSBpXYux2sSShHyN4Gx0ulBXyNBM0N16FMDm1dQ1iTIzjWU6GzM5EY5bq80uGecgHe1rt1datYGdgOmMnWGSgPSgRBXwxoOj6qA==
    postgresql-postgres-password: AgBjArLnVTwzwkGpG5NLXU07R+Qdg0IT5ng1lWJ0x5n6yxUL5ZhZ5FXFyRH9VhpoClIDE6hj2bT94+Zw5GrjeBSWIO4fxTdnGMB+CaZ0FhYvI+zHLq/T0SbAL7QW310/pE0jVW6Ff+3C542e4XnOw9nJsusUns0dmlmXDjwgsSqdi2iLjcf05mMRoIGAJCD2CedhjyrsuHOMTZz/1vzik146fm/zh6Av84DUlVxZVhzG7w9bnDk/I/7sKtg1LWhfSBBNR2tSnL38/O178V4saL0CgLCUsbVjKFJssw9pEkNMuwNDyEXI4LJ1cPCSGZuFmETTrQm2qxXjLGVSJHIBpeZ4sAp+TDz25VjO67xBP1oCFmoi4I4EhLOa7LDZKPryvvMyKkZPNWvUtslR00dXcdVH2/6aYZSW5qZKsNLMvS+Zza1FROvH2XMMdFMt31nuqyEFyJtWle9haA0OqMaxkROhGZewJ/p95nibTek5jyfnK/aS3j6Ese0oANGkkmos9m0LIbzksV8+nGrsUCUWGFXR7daeJxPVKBAw8uFSo0GGTkWKaDx4mCSCCdXXf6ZnuwJ5aRUf7oCUPmWVyTvcQTdn6RmfOgvFY+w3WBZyRj7+q1oNPd5IzidW6rt/fb5xE1vBybdEyBlEbWrQhNbkFPgRS99pBTnn8jBhlAAgWLP4V+t1OVppNnVj4pvMVVbjTJ1thTNhH76ek6+NWGjgNXm/52M735IxfDxk7cCCbWeEqg==
