kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBuAcovzC5DHT+EM0bZOtmJQCapmUXlYlAsAL63A1SkeoPfPCJnq+IXsvZdwL99NjTJX3+XGutmkBKztAMBy3wuq+CMVI14RBR5Dt4u0GTgF8aBxoOureV3Dd1VAfeNHiwKFQ3jatUBy3X8lXgImY5X1MVYOlQUcil7sSdWejSaaAzrb6qA4r32JSd2Y9G8yqUCG25YmvOz5G2L42I9uzUMi4xtLBsctzTtMp6TkW18ZEShFuwvcyE2FwquEOp6CJuJT7KoSW35MjnGOuERfcoQjbujaHGOo3P2Hwt85+44I11dqcAQRYZ05A/1pcSixJM+B18giB+8ffByEkZkUAlRN2ITvDsNxl1Oap80S0G/qd/wq4dqodRiMzb7rwwdYaqQU6pin+mOWbcqJpj8w/JTJhlT01D/Fmoy9f4hGwuJ5DyhCZfEptjAGvTjJMz9G86Ro+c/xWEDbv6q8ZAanfcl8HNr6QndM8tuRGJk32G5FidK0Y4Xdvk48bwsdoZ6lpsKnC4/JfgKebeF0mb6tSUj2u3z5KnDUtoCqoj5lYulDobIFr2TBcjyktaX3FgJoGlJKrqjjJkZjy8NC6V/003Vg4/zc70bTnEOJ9pe62acnuFIvklSNI6oDLgtmhEga7du1/s8Pz+yNbC8yPMj9epjzkXPss4ZHVGJSiYBWa0wPXyRYUxqykNKEsEHr3PI3TMvbSzr3UF2ApUYykjynAkpccyzod8bKxAzGST61DRKuA==
    postgresql-postgres-password: AgBaiYLxkzK1gMgEd4oDOl2FPfbEs1UQvd59Spk3eouWk/bDxuyhVTT+5G+v9jSbtW2VlLrndg1NXxlG2tjZI3cHbv9ofwN5GIrv5xQUw3FFXnBTw9ezJO+6wiehtdhktBJ8D0BPO1aYyRQmOlzjEsquPe4jqd1b0bcxQhWbJyQSydzO8ZuCsGsaqm/3LHBfLTJW7WklUW0n4LzzKgksrTZw4o2yewWUW/X0oo7A8vtBR3ZIfKEq8he8TQ+hmXFbCQI96mFrzavXjfUJykwgqxRX5YeGg9LsTNi46ucNhXNjpIedsHZFYxFi3ZxrZtzY5ke3YtaJVZ+RBn8Hf4RJVWMxpU07ex1HNmturRALLV5X5NEMbzFya5vn0AjzLMwnDV7HvXKej0RNofwsYJ0JGh9j6kN0JVA3N88g/Hnl6Sx4lq68zZ6A1hw/4gMA0YKzy9HnVOsbfz/PNUbbJIkXa2qWN+CVyLSVw0/I1ilp5xAtbhvuXUE8tMCFbPpgz6mRm1w+SYmro3gISVZO2VlMEhmiPwLmiS1h/fTZZ9/0kXb/vJXzyH1PONAcwgmnSZQ1DK5Eb9lpY7M7zscbkKO1P+Ury5YFNUsBviU6UuI/10iLo7ua0CJDexHL1fR6humz9bl8/LSKEcLf5/w1grHZcLAKTIgIrJyadU4sxB48j3orcZ5naoUNzO6/2r8e+weCmwAXn4QzUh4iOoHjjf2n/czO8ALNoZj+7+xNBVvceMUexg==
