apiVersion: v1
data:
  static_email: none@none.com
  static_password_hash: MTIzNAo=
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: none@none.com
      hash: bm9uZUBub25lLmNvbQ==
      username: admin
    staticClients:
    - id: kubeflow-oidc-authservice
      redirectURIs: ["/login/oidc", "https://192.168.0.207:4180/oauth2/callback"]
      name: 'Dex Login Application'
      secret: ZGV4LWNvbmZpZw==
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dex-config
  namespace: auth
