kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB3CQFjf9liDd/K0qhFyQFLMwDi83rMApWantGOhiruEQgukqvBDgL4+eAf3UA05RYrhsqIhZXelGF3IYd7zUR/mCUgFom/sj9s7un4756vwLuBP8YqaDbUbm2QtImCQ3kJDk6UkKbdP10uorzbatPX7cFAAaJW7j17TYWK1qCviyGAOo332a5YJS1c/sIUNt/jPR0gZEIu0/NHhK6PfTGzvB2BiEA61Wi/CNPQ/adRk8kEbjob4daqaWaOAvvv470uO3COmyJcv0MOzVOHj5aC6ANJJnStJuxsMBXMCS7eO2ZiiINoRmJdy4UKawZiwU1tdNDUljx+3t7iV6qybXy/2kUNtDx2XUAJgswsM3OsXhKjftKp4HnoHV3CZXFGR8TUOuaNFmdUr+9nRDlaUineLkpXEr7nVcgQQcQ5fqjgs9DmdEJog5TQUSp1BMKIXJ4Z4dcUQHFdFKZD+zL7jgtNdio/gSoj3ozoiOBXzWfw85RFUCSa6VSLW3iwHB2nWIvbdyztHxfVt0iGnIoZ0MpMCd8xQN03CSXQ1tJk01PT7fP49zD3ZltfgHRC0KLAu89yZr3gvM6MVP/h2Cfo7kzb7AYvwt+V0pgrJDtUdN12S2q6yYYK7PVvadga/aHWfhMBl6E22Px8hIMzacVmai4cR+aj53LnsupMmKhpJFfN/Hbl7uXWQY0dH4IPjNQNEexJ0l/z
    admin-user: AgAet+fZUmoKeGxyyQc3Z+2lrhft/BBGsaYd6iLfKFbe4m6T2ckIqJA9k3r75xpqt5M6SyBs/8i0OHJRJvG55mLZbmm/pLA9R3A6zk8UYuh+reu7rWGqVPQmNGYBjNLe0a7ghiHbNqOFqKM6IKsJtF4mM00M48yM3Azfo9OsvRwc9+n+6evN5kmPdDRTaqnTCVs0du6UoqvHCpTLmpmIfHnar88+bLPUHdJ4+RIndTrC88Lx2EhLGO8LMOQ0FslUAYXsMnFi5XjllxvNtAe5Sqgm/4ZAiYlrxdDD8E9MLN5vPBTq5xqxw8t45iRC4dbq/0MV1D4uoDkzri5VCj/0mOEy95+UjQ29/QGeXWuzW2MtAnkTdgRIUKvy5KgcJMcCs2A57Vl8LeJZe1gkfXDp2kH1ihvLuXMG+iUWx/5zwoXfMt69s5642J8foGzUhSBkmsfcHst6I9jNsfoNXbcjgLtf+LaCS9km++yJq14nzMpKBcfpKOekc+7cmiR70W5vZK7vbdH5EXX83oqa0A91MxFgIZiVAK6QjaGheGvnvTSePex8yt7JJ+YTiVt9+RHMOEuJ5iQvS9jazZ/D/1nNkt6gsNHI+UiaMQn+72Tk1jDmmzPfuW/MN3UigzDbxDZ21TtTIQBUFOoDGtxbA9NsviN6Yo/qOnXzg+KDIK7DoXkiMyI7eNeRTC/+1Fb/sxAPM9I9fQrcuA==
