kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCcsP1aKTMfiS8GZ8paHWSdF7HpoYtY4JHm5FNjvqBVMYMAItaMElFe56Bchscbb38ytTgXKu4AX8dHwlM75xaneRm1Uh07Isq3NXGYQsDDJu6pdIxLsBxaOby8qdHBshHrqU51VlqacMDuvzmjSlPC17hiJCIkljb+Y9OqZPsZ6f5AK1Dd+sde7jREHexYqM7uIOg2JSKN2+2k9ad+tHCZ74tdQCcvgEDON+NXy1ijvfXcQ26ELIJkbiXm7RAJex1xnRvFroP7bX8b3eAgTx4fgBqsD6oeGLmO91LGupuwxZle2+F/y0ACaxG9HtJ5fHKHVjm3ZVRjDaMOPmIUOiyurRkrKW+r5rw6pCC1WI2NgkuV+ofHxaqFTCojqv31nAAW5SnKW8P/Z8eHzfIuX9l2cB+V9FCMut1DJFCdcJTcB8Z6sczzRN2D/4eDpOVBL9tr4Zz5kkHY/i2FLW1lNrEmKRXfAd1Sv7nC7CMVXD9Hk9wdvwdD5c4py6opAWuPx8sWkhrTXVzCVIi56Vgrxk7dwdKzD5eS3OAjFDVi4O/RWYQPoflT8iJgD74MaHOOneeLjv3wcB2T2eBhO7VOmtHVcOyRyvnhupdCMe46k+wyz1KMOsEjVIcjaoiAMopfCdL+/FRnNQiAacfDU/5WZ9CoJOigqjn5xDja0ac/ZIARkVXv1KgAyycv8Z73Oj9q6s2r3YDb
    admin-user: AgB0/v1QeU1xUC9ijUF2LQRgTzACrXh0Ys7Njv8W5XUmXAN+D79g+7Wpu20j7mysaUJ9NFusbenodEKzD1T0esWGlz8DVLcHq9hi8Cf9mdnK0oBhX70oakzqvu0OUVeQD1aEnf93lQNaH1nsB9AIJpHlLvCFXOIaw711mWn79o5DhPsGrZcgr9qKRK01UYyR63hz0RQv5CvhARwboiKclHWa2kl63z72azcHi6pNIct0wyF+0jDkzrpijiO1jm3cBY7NvUm+M5F3nooX6LsCgMTq96X8NWvy6zNjAoXzjVH70T9DzhqDCp5xHPoDXl+DcTNO5DEL/pmMkCz+CDfm3FgCjG1G4eEac01tHZQbZdNcDNtVIbS1k10w9uhWRq9b/m86RpTepA9JukcJJY+FebdNUEbf9TMIj/2JSH/q+H/WcENnmhfcgbwGeWsapGEfsBaqDziLa9OaATrS0vJ7M/FbBYCCQ6GDXUctyBngasMLL3A7ehAH/TrO0/75KYwa+aqCyw1fJjI9c0+eoKDHS3ES0j5aUOaTB0i5QVBJdoY9G615znF4o0P6Ea5+A/DiYhTwJ8C1Wz41wUTWgkTKAejU+YJ1e+2hXZ/JD1kmkBCYipNF1xk+OPudA37MQofCRsPNd5B385f2CDNcWcfDHaf3NaU5kMZcTDRC9dEWg9sGrYBw0+AoKw8F1bB/9NClnELHD/zFgg==
