kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBJrGBN4frpgFZIsbQJBn2pSma7yBBF7t05RYNjUSuOhHJJ6mtlhTneoJozZ7dPoShytgXSHdUbuEcPE71DOvtorQ/K1yHazIZgpITm8zNQ6XoIbX0lJfhgzWFZKQ9HFeJQuXa1vDlMXfXBEQwQatPT+sdnj2kmg92x39vI2RA5nDVDisQmatYc0n1p0JTY7rXkT4sxDWPtkbprwwp2on2/aUg1fpjtTmh/3rsPtwXwimUJXQaNG2eXh9cOClkWyixTq8ozsBrbgxFzKUDSctIbAq/FXq1rQUSVBuuwc0GcGOk5CrFZFb2ug9exvGmSBpu9kncFbu7VFGgxhtnWfOrzZ6IcpL2TK5PAugI7eRC3iHMjzt/VfMss77WbuHMd64TFJdeS2gxJEf6omB3NOYiyIabjgiZVT4u3MVyJZXqNDdpOf4vio/hHgnstF2sUK4UnkXQQonQ6v6mXhRTggRmkWrNOBM9gmPfZt67P0+k190gGwmp/zHrcP5n47fRNbkLtBLkLZLAM5zMHtfUm0eThYss0Oa7N+AbcNrnI7KUxXBNt4H9vefnh4ed7y0dawWELtRBrVLaUAZNxwGnpqfL2APIkt1BcN+gQdXLXFhYksiLtvt5WC7UWBhfAbEq/zuQAMPJSLIkgyQ5Ri35JjvreTk4ZOYaXvbnpHhobnf0ii+CMFf3Yuny/J1fcC9KTu2QzGNzH
    admin-user: AgCzZEPhseYg+FNEDcEfWuRIetcuSbifwEnIgr/UfgUSjjcUgkexIjgLJKRtcCi8qYAqIPYIfYMZOsvZCQplxLluGnMJWrNK0NB+/YRCT4y0O8b1uwkEROoR0oHiXN6N7/zugE44S/5nIOnhO+J3RmTUAP0iDXgPNBPUvca/uPgdRvekUwnvt1Lj5SuKrD3PWo8zh6PY54eMxGjKrHxYjgILTJ3DLb5+VBMADDXZN02xpUhHrvldHcW/br4G/KHGFX060x6VGjYyzUKgaHtQjQudBwO8fM3QY4+SIKO1assvy7Lx2ZbAziz18O6R5TtcBJSkje6kjlb9EiRAk3ErkNgq2Q8q8t+8z46TUTtiJgavtLCsAlZVprk0kUXgyDClLDRvjXcQWyEAk4zVKdIm5qDd8FyQpQFdWQ/PcOBAj4xr/OzsPuUtz1l0mAR7WDY+1EKsBcSRt4Btmsi0K8EXt83y4MJkixxaLxihiTIg36qSBtLhNRpuAAlXHkUQEVkNEBsXPf7EnIkRYBNp56xLih8Ju7hsGgCeLTZljj2w2DXPsq2jsVwp9V1Hi064Uug11o51Yom8mcdvaAK4iupK95/1YxM4YS5a2TE8C449n5YHP1fI2KfJLJf/u8gr97MVQBze+jAbaSt3wzJAUs3GwO9WRpcAiGBY+oLkhXCv0knH0BkBnQiPP58W71ias/jK9TDuwKiLRQ==
