kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAjqP46Lpq9i2uU1DjQ6zOB72sqzOkiGttOOxyExwpvAjXZ0ClrMzHmZIzdYBuxMcTL66TaOijPk+QtnTQRIVjC5d08+/JdH+FiKbNypBclNXPHooq7006c8XoCSAu8kzMUQ7Hn2wwXFhgKWofZs1qn/FFmlfSAwhRpZBvU9cLYkLnE/53lILEsMBR/XFw7s7gOjscexHfY8XRAnP2aGCSUHEKPpXo3yaKci2OzZO8e8c0tZuIWUJADZ3CBBjfxxddM5wFRJJmd0z0qdMQ1KiG4n4hyMbnj3dleSE4NZQpBRyDeRWHqcmcfFNMeg+1as19+GFe5htEpQ7inr0n58ZEfQ5MvCqANMLA5uBCvLzdW3SQVBEOlx7YWMNaXLpK7HnRrdNdR3CblSkc83hAysn0gBnVTIu+r/Bl6AHOhfgfWYGrHpOHhhI2kqg9FZqwIirI5vVqmTb17/9nPESv5dE6EVtDNa5UWYVuQTfiUuDPEMEiEySW8B7qJcUXCXlNFQpbFJjYzbzDvp9/9s4LpbxFBGes4yxaX6U+eCyII8Rt3IUB5usXNG8DU5ypfyNCgnV3k8nUYpJIaj4am9SbIf3UYp4oTIJ+Zs1l8bsYqVpby45hoevN1ahJybxH/OqgiZ3LRhFpCc4vEezTecNkGdVoG5jX31VoZgAoNhkA/XwvSKxi6IPjyuo7MrTAbOJoQFmxS50rHzq0=
    admin-user: AgB/oGWWVjusK24s/Wp8Y7e9aZqepVjqwoyFHDSMP98Zlziff4qcleavqUc0ebeTKdhjfirdy9Pz4q3Fo1JfEWTIM3qwSNzWFs1m6LLTn0M1KnA/BGS56mbWED8lXT6U2wAxrgGc2Q+s1I/7j//t/epVaqjqk6aKLWZK1uVtJSJd1g+87JEDoijVQmmnrFoP6ZA8NigA4RWKdicFFpALw2u+xjk7X/LdsCzcnAirrc3tRhRsI7EYD8J947bv/xGs5kvlMIvztkOGsrrGS0P5MUulO2jYpgwZhqQEjkKNxbHy39euWcnAFUTIdMNt9KaDkRcaZAJvIQ6puO+0ixA3+w7dgHr7ShHFiOAT9tdOHa6n6YwnTIeRcUF9F/KqH9OQ1nrikxCX/E35RYxbflRrh39uuXQQmsBGitc7LPCpWgx7hmG5ucvDvjUqoWqczifye5mITq0tBJZliEwyGbGI1D1ey9Q0H1BZtlHYc+Xe6YajXMy8qeQHDl6DAJbQsyFufAiZUdcNw2JCpjZhsIOt+6u5Lv5KMWqUQ8mtMK52m3+apx6V+PE1M7MXdz6KeBNE68svzJm/g0R4HXWH8Yk9NFkt2U+CSXJabdqHRdzcjb3otNwvAvx0ke7trZOLOcDAE8LnMeyg6a9OhPlL8qeIwuSv3afgv5pkZVHWT8h7nEaeqV/2YzFLLarGvEIVc35NtuWB0i0DsA==
