kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgANvqu9sPdNZKZiO3Y9gelLkIjOd/6Vh/wyMivpuVzUnSLIFXK6ZPYPzfD55WJtPZfzAWmjFmQQ93wNMAojNsAV4U/LOixtZr1QXsUeiSZMq5fQN1H+SNETDNyuFgheyyyRprtw9CCib/nJniCMRb0rV8WxKG28Kg66GgrQR2OhuqRoIQfng1QEK8e3spSsXx+ALVOeIZ/6NzCkETHn9HoejZNwamVf0F95Szw0cIHG5EHZLNZh00sgfZxlfN7l4LHouKYaabURs+2kzIelqXMUEycavRST3H9wz9JZeG7ojiorevuPZdnG5MrEiYBoEi1KSX5L7eCvAqNXEikOR5d9OmeUg4RVdj6KhWlT2GrLj7SVPpoosoTuGgR1OiXo3dk9BXjP0U33bL3Nt//boioj558XHmlCOlnEcc95DcctOyledDxq9y3aQR0fprt7S7h7GHYamC13Ph+oJFTJSVv6TN6ndA4bKhPjDw/d8llTVl6i4Nci3EKzty8SxSg8vPDs8o6qxaIs4i//xYGjQjgVFX5KZrXgLUk3FVuRhp2Cnk3SPe/XVM7I6cMRPomUjwBA93CMp0bolXMZOBA33vmQAMcxXT1vzLWbWJT4lplJarJN2Lffb12YegZWTPBXfP1bjOB2uI5Gzf2/zcS6foEYQTQf5VOW5vV0YyTcCzRtaZB7cEaBZqC1PWz6o/2Yw9mP1lBC
    admin-user: AgB1f8DYa1e2ZWOXOkDb534oEaSotzNqHtxfwdPQj5a6PZoGmXluiLG8p8oOffFdZmKgQ/EyEEMPnUHJ7r52Nzlva+kNI6IS3hX5mBUhRrBzxbJe5j0HsbIer0zIPOo9JftDw5s3eKmoE23Vc1jCKBOkBhwN+RBzd5RYVspcfQQc3GOmBCqP3XXQljbU5OBoLsYhy6b6gM/sO70Hr2SRtlTas/sCVtI+N1AMJmFBzGGGtkPpECHSlOKg1vUpoPDLGO0D8l+LIpn231VZe0kxa26sXQw+1ajsonqHtrPk2EIFbdkJgfazNEGW3n9BlADp1+ZLpiLnbd8hP42aLomMBw1VJYtXdOgCC/rMTDPYqb/1+ty9EQSNuCW9B7el5dpBgoZLxrHHe/RyzyAmK720sPP11u9rMOlkTQd49j7C+r8indK49Swe5KTbfNwP6Ysny9nwOo+icy93UAeYulUA1OaGNKnFphjvh+a2Lv2KHa4Uke5GSqG3oC16/Kka2/jFqgNG4FT6KWo6h7IA44dJT9w0iVKzj4O0Pc1hostNAywkYLJT+DrFQb5LifsCZn32Cbdz/FSQZod6GTBZPE9e9gj5erV61wrI/DhRGpWb0gH6RVnZNljjJuNCtqYJUun6oVgwt0lNpBxmvNDTTvplrVidUrSK0WrlaoYfpCGkjEsp3mvBj0Yjeg3Xv3RUA1+J8+CaMw9l
