kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgA3/Me7zrIMqScIooALLYaKvYlUtDRcaDuYQRKoKSV6COWLxJQ/A5wHNCMhf0fsSFySFLbvCraF5//ZoyFNuwqwm/IoVYJ21dRyRXVwfRtviWutJBWeeWfW/KN38JdY1flbO3MEUVBViigBHFtQaj4v6zneZRaK1VlVuuNZ7v66WLtoceaYwcuxAtibO8HC+cJ2UcpvYcPvlpBh9hWMK+591uL6dtSWqsAivZYG2qODhBjBC4CYANKfvUiW+ZVF3Ix9/bIUVH63GasYDrDdkbLPvAYfmmtSHZar5tt1ffUCpsgdajYCvKSaYxqdojoV8Jm7bNR0Tiada8flp8oKzJln24n8C6kVfnLNudZr6HJm/vbHEWDk9sXW4ZZV1nhs1toOKvZamx9daEcn9HHO1SDoASI3Q2w8VmqEYv43juuzV51MJP1pCChowHzUG8kWydiRSY9HggQDDdvAC4wNKiN3HSb4TE/+0DAhcXOn1YhaCL8epkL9va/2o7kMk1AKZfJs9mbEIEJLMZdi0rYGlQWAr4ay9liMUNpowZFB3KSCvM5+SVhP33vFFsREhSYSz0UbNSFu1UUGZ3BypHYOEk0OszfHKOhpplnVt9FGpqEfQmwzNw3vdNgN+679kBKYdwtFKaNAnRTlPgqP+iZ/bWdf+9ZC7ApYynL0bQn7qFXoPA3N6A1kq3NNL6OPczqQ0ao8E32M
    admin-user: AgBcgU5wCvaVq5ivgPxdJm/Gw6wMljZyP6Ug6gyHodee4YOIM+XAwAMULnmr1suUiEq5RmM28Pv+99XW5+kO5YXAcCb4HhQGop+um+BgQOfFpTIq+RHfsVL8hPOjMPMrNw9AAYBKHqGh9NWuLQ2zkT1+BkeA/kF8WqEODNTqdE+w6jSQ1HRCHVeLqg/wKY2XkIsCn8Gx1Lu2iGiX1VsMjJRzASoAv432UBVop/ImhUodZZbILdk4Agtgpgl5jH6y8vJShVhNhu/itbEjxpz/74J8VAbzwbNbJMpJ4ZuIKZMYlAfn+Cs0KuthfnYgt+j/K2roEPS7srVbmgiV4FJgrO9StA0dGOGleQjF12tkeWST0C+PnOv031N2hzNw0CSYwQ9TcjcyNm+/dUeJBpLtVnJc0JhUUggdVhvTZ5iUNJaFDBJ+M+4TGQpk416LywfMHAJ567Yq6HCJ3bsUvkAQvTMNFzoS96yRFtI7c5XEU5W61SxpJ+nfNnZUFh7OcNYpV14WxG85Joaf4Lpijk5lSsUSt/EACQ90vJAwHZenorOWq2pd+cNpVXptAVSOkZ6wlxBQthtsJ+qPz1A5D0VlAIHxJLYpVNyONEN29sxFvC8bfJNdtY86pbcfW40toUm9xFt2mH48tg3/m9Sdc70KPJtDxJRGaXiSHN4EpmKwOklHJI4FN3wlIUB/c8TJEV+U1a29DguKLg==
