kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgDTXbTwE/w71TqdWr7FHFaKmvMIvuqGZaKVJVQapbA3wj6eSOWhMj7MxmVMgagrNwj8uNpd/9+0G6aJGZIhjlSKHK4oQtralFel/p28hvnTsMof+r3HItq18eAQ72hJsn3flmt+HwwoBhY7mXjTulvPQMa1wTngN/6r/qa/jFZtdIRg5djV9k9zN6NnNbkTTelKIc5OqhhEDELGuY0rkbBWzrzr9y1DsLz03Qz3/L/2iBezEn1Z2yy3/pMKuPqY9rxlshk0mtD4I5an+EG25jJerypdwHcPIpq+m1uy9Gxp/5Pp8GPbtFCo0vjKUJeTqD9l+E/OG+bkLZ18KFqHBjKz1lLoYOC7KUkFIEXZSnFXUI90DWCLHpYuTDLhiYg+gi4U1vB6THn+sZbSoWn/7/DL3hkccx6psOVcjJ9mAgMdhj+H9aUVyoPrKcDd9ZOLp4VwyafdPl05BjqRiGIJ74IW2zzURII5z36Uai3jlhN24lchmjBVAO8ZMWMJP1S6M/LhGsEDsP/iHOk7LbES2HivZ49C9QHfme7pc48AtDOAKlbK9KRydhK+vAu1LiEAFaHSFQ9YhwypwN7ppoD1O0y/As/PR0BHoTEDbV5fudVlDYvj0+CnbEHwhhtfLzYGSmaCszQRXfnVXRbfNRpVpcy+//wxqXwj64WNyjp88vcZIIJ0y+lfuzgd0SuOCN9MfrgwswFQ
    admin-user: AgCgv9lKQdaw7uVLJTXNTNL398Rn9WqHGunN6Tib+FK5reuMF5g1jOF+6CQv/RLncaqQVj/yGBIB/DIt01b9WFRSt5+yVOH/+vGVNIC7DKQhzq+IBOhvXookcw8A0sTMiZsrddSJ2dlTYsyvhMlttySdBRjFiRk6rtvn3i0wmst8VbdhvbN+NPDzBzPNAKHn2I5tnaYZ0Px8IhfErTk9eWa9JvqSR3STTBfZFOq9mrrlAiSBo/zh8GHYL5E8DuAAzCcZMiyRL/yh1lcqQm5+2Lt/oyyB8tyV8vjX/bo0mMOHwg16EBK3YJ5I6b7f1zZmGt39FszCUFJoLokdOQGKkaZSTemq27bmMR4NrDNnTkhclLG1XfulbfKSsxY/PlMvouNqJKQ05EBZOag2i3H4ZVxIC8EiDTS7Xe+4nk8ERZrKPpejqiHEHWkXzz3kVOjgWj6t0OSmgaiM9E9vebLtNb460EBEzbUsUE89RBerq3BcmTRkXXa6bFj88OPf4PQxw5m/1Bx3vfPh9VWIQlOL1kyloElBZOPjVgXV+h7ol8ucY2COfRZ+x6UKjDoUOH9/km5frF+2hZXyO63a5gkAeSQ4S3f8A8N94x80xtPmZ2SzNwn4PSrvXb6UeiIhpkOByho77Aucm9cuqBRuRGNpAFFG/Bn2W1huo1IDVv3OgPXR8Jg/bYZ07zPHc1r7tkg6czh2/MAXzA==
