kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB1UTrVJ1n2RE753ydXAT0PkS2T0EgkUHwa7O2dEXdojay8i6ZNVRrrKVGyM2ZuISzEKWq6O7Qtxfg0iC2LkIdk76cHbgnWhjFcu2zDrS1wqXwbZnQ5K0gfyoT7aU98GFV28ZCgLhXhlMKlgafcf24r1UPPTFZuWgOxezjwjuqDK3iudljK0nVbKRWE9I3HJAOwmoQdA6ZYXIEB5XQKb6GRrorxwiGWxP2A5JBbMjsYDF3uZtXnvlpsAcycg77BGGBAU+0nmg+05gTEMA/zrsoB8v/t5luj+9HfLF3SvxOTIeiWZdBeL6EwKTs16lMuuYqF9cYWwRyWfIwegS6BY1Qw0MlmFIo/FxA7D5vQiqjqACGCmOhT2yD+WDBLzLwX/tdl6kyYd0f4JdsTZW7SSj1hDeloHCmiVZjiP/DtC3baGzA4pRDo/WSa/qxm/OvGBHrbyQiv+qqXNuUAt13Oke2+HcZG51Bfy2C0DUr1dASLAG8ZfLuSTF3JL5gQSamEt5ljd+GuHtbXaIs7wkiUV8utst0+e0dAJB0g+6iwGmsMs4weWE1SxjiJmbQpc7shrJhBmeLePypsqjEgoExoGkGjq/iM0zDR/6vOKxMKCmDcX34tSVrnesaJnEaUmmVKLWDbwvybH9hHfnJk/8csbzbFJE8xgNMr3vXDrT/HbzsnRC0dkw9HavzRv5XymFg9fLwX5qrC
    admin-user: AgANt2mnafGfmeI+H4YD0Hqvjz8hm3Y1jgRY3xxFwz1lf33m2/UQAtU+yQno7EVvN+vDlAWvgg15WO0zvm/JuhNSoEJ4tUSXCCuEc+6XBKMwaJ2J79vSgfEhmCI1FerR7lyjpcwaqK3G+KPFZWr9HFspXqeB3LbRHQ46sAEhWBP9azQdowmAT84GnWWm1foZOtGg0moQA69PiaT7KNwApyc3qgmJDh3g8RGx4SNAOYCbVzmxmjk9QIWp5NbGcq5nqcztuuc4K3XlGYK5BSYdJt+zuNkKg7yRyIqOH7IVIp9CqqkokNUdPE+nJl78CIuvnsBXAMnJeQA+s9KlO5kW57wHz42z4xDZ3NK896uAVz9lRVxXDp9rZD4hL5lkQio1WOVr61t0rMYdIb9ElItQU40gpgwLSa1IK4Foyjq01RGJnfZQ+85jJYXvE8xPyTD20g0zh0r+vsZZXhVi9wdYqDavNdRfaMLKw+bj5ZLeTkkKqL+odDXFU7V8TzA/gYmLOJshv6JUs8Jwrv4sqtBzr9znjBx9GfUY9GSvytzeFxRLwmkybTGkM7BJWxE7t1RNo1In0OoVE3pUS+amHZcZ0nBFaszTmbVLdk2YKNHxkrCdEZawp5MaGw6NPo+BD6h40zvc7j72hRL3lG6BACS9l8u57GmWNAZQePbxm6IKpO4UBAitVyVE7JsiT/k1ilAE2f3IsHpr4g==
