kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCW7S+3igS3hgxWo4ZbaEEh0IGvuvs9yv7nBm2VMY5Z3XqVG5y5N2Th3+RrTsLp3nCrbo2vj+g62s3racjdftjuft9VqFIEVxrM9VVsQtnzAFK2WX9BsEoisXyjKP0co1j4+/+wfmuoHx/0qtTr9J2bkNL/qKoHvQ5f+nL13KeWnfVd1V/rrY/rEw4kxexeB3k4vO2mfUP9P9/0uyPF47pbdwVD2c0/OZFZKIM7qM1rVExBwrLIsdUljk6LbH7Kyc2Cs617Uf7GrjL+qj6vjy0MPhRY7fogxbe5ZeZGeXa3KJ+xhkO+pDN67jtrqJdZ/OavtsGUIhaXLJC/F3eKFZKR2YXf2ZxlK8wM5T66R8w7U0PUO691eCdWq605UK1rFxxZl7J+9G4I+5oplZ+/8cfThRX/Nku+OtBY7JdLycRR7wUb9DyucG6JfHM8+3UIsRz1GIZ64fMEmL3zgPDNTh3vkQWBSv/AltkkKl/6QgQXzaMLLQPDr2W/LCQLIQ2/9juHHTCHl8Yz6uDce/0pJCHmIWtcNKz62x+hJXyk+xuXcV2H0dJscQiERrHqOToZTAQnYwaE8OOB29Fp1WCdEJxrpgrYxG+cx9/wa9t8Zbf8GDXjTfK6AEnopCTBpz1egDjbKrhPSg9W+gwwj5LEoyEF0ThZGaU61LN52S7MeMKiyh0pAbfLeF5OZ+srUBhc5Q9je8E4
    admin-user: AgA9NV/nCk4CEwSYomR9d/bdFmba7qak5i1Figqq/tfqy8x5R/KQpY/HoSLoolZtdxdsST+7Wc6lldTDXBVC7K2gHMKN4tpMKh8+kzTcOA7RdMDhLeO3OsIwMKKLWi/0kUaShcV9xKc7MxxcXx8t9wI7IgTCs7UMSBRjhwlU5VBAcienAAx3bNAvFUojlyVqkJBUwIAzE3rt8ilCJcUOmmQoCpS3QRC/HHZapjRqx32iCZQX+63TVCAMB9lwB+ECjJUHsLh2/ofU5kyWMP99CnUMK/D2Pl5IrGDn4aIPmHtsPy56O6fVoMfPu0D1WUh39vsMa+nN7ZAL7EiLtJrWCOpetSN0vYD79zbkygRJpCzCrL+Kt1UkxN07+gZAw2eJyjwyjuWzuh38E5WyyT4xvsYkIQFh6B1XSjW6qc1MYdS65Jb+pNzwfLhc0uUHWHOzrmQgDWmJep0230b7yFXpF36ooyU8oSAv2JMNgVTxHIoVzAobva+bBlxZq4Zc41H0yU1ELM2pIPWbqgteLwPp3DDBhLQyR9i0iE+iekEeFpxbYR4cZxhWx5vP7QUXFCEjooffVH4Whzexgc5RQbAcjiZ2oBeYHXWbKWnmh1J22c3tvU/L1Q2RKgYygLCWRAzyacGNn6lIeSu52JhM5y09HkQyAhpy1NmzmGkfkJZ+TC2NZCCm1UNxnP3j753ara1sCbQReBptwg==
