kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCL7aniyp6RkSRgd1mzJqcfapFMBB3UDHqaA19M41tWUA+aYwFGz4/00aPvsNidINI2SIHODGigCOV/BRvGgL900BrtKEzk8Scm415/JVAU4x10kbDVqrC2A6ftkGXd9FVutItRmFpi4FNbVcroiQepUePswSDiSKWB3sUMBT0rtQRWGV2UIFZmSDkKO07T9j4tjGe6mQhoNUPjPiJWyCVQldAbxjo+55bvD4wgRYhToZkyXmpqZDOsOay5c8CtDp9TIcTLrHhhrk1OOTLDXmOXTMxJ7zycZ2qEg078j80yfRW8TQz46bwszrNZ7TCx/bUE5S4EjUoWXh5qBtAAZsPS3xi5Q4AhUv7I6UPFzzYGucMMD9Zwuxqjvisi3Sh+wSn+6rx9fR2lnnz/jKHgCd44A3Xa87/7gYVTSvD5brttzcB05Oc4LULstOIurqzoQq00CvT6Hv/K3HxgfgI2ZUuPx8X8ugflAr9BnGLRwO81dQCdLgh0+IDgw/RVgDc4j6xfEbVqpm8vUEyo5fbWYxqLeWB1XpFnGvdhxHtONqQexViQ5NceNkoOC3pGsNU5PcPeHr1Lp8skYPu1Mef+A9zpiV7d2eMzWesLJgRCcbN7kfbzla1LxQQU5oZYjM5VX/eCCbV64HQjZ76t5a9L+a5omB1+4KwXEKKjf5Fh58HZYLaQhVIdQpFfDZMuhUxbb8nOHVSQ
    admin-user: AgA5fMyMCCZFPK4TFK4KgyC8ms9buqHItT7mCJBAEy0+0wLGXUiw1dsU/49xDCf5Q35kRIlEoPcnG8KOIjsaBzBK4EitnGUbT00Lb2aCSZgz5fsLMm6Q/7AZlJnXbVGApc+6ZmxlCTPQb4czTTmSE/01YCHQHKiBREE+jRpVohzXM8UK4cP2nRlU6b9fsXP3McPMwZCSYko7+LjpUfTt41en7W/B3V9v1mop+bXAAz6Tow0p/J15fwjaNU3V9HzjTpXCQV5tBkGqxGKIXJ4WGbh4m4DlnC+QVl/QOiDEIgph2ytUnAMJNxflifDqKeSXuRwcxi9+Gh5FAyA+TpfXil8XoI11nisrZrLTgkohwLfYU8Bes3ltdmNNA0PWl9mjbfDpXBkE9dl6K0bkH8wvw5vU+KKulcxa0sSNr+bCOFivH6LDRayQ4TNLUuyYvnA19jML7OGnxaS93MFJmE5d5DS2A/OJpYrP2sctY8KbFoHvb8p5y02KAlXfEqcfc6Tuq+LBApwjHbhceYGbgkshAEGRs8Cnc+obb85GJkxN0+LyfYz06R7RcXvLNjfhvv3o7B7c4ri7nvKeQlhIXIGRd+jo8xf/0B3r91BlTfNtJbgxzi6idHwlBcGtlG3iCid1VciT3anan5e/eaLBm2xyAq9u0mfVkg5u1FxYl5QCcwXF8WFvyvCJGceFuijwyonnl2wTclwRwA==
