kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB4hv7ZjxaASJ8jQE5mUN6ptAyyDhB5nPOdf00LDVYicMuAFF+FwF9IpmcpyknGV0WzicGpr8Yd9w13DX1vxPdHd/tZFUm1BDDeKhramZWT94k3o2TYlarA/XTUqRXdg5/oPbgIIHP8oUFAnKoGq+QJEyeQkXlmN5jluEpgfWjk4IhvhAzwSISGd8AtvWIJr1fpuV0c+03cI44p8R/8Ul62OmarwJkeapBg4blFNkeCpDN2/Z/N34ST/2BGdkZ3PKcBCES/cc1V9kX460gZOTKcHEEdSv8CCE2zGbph5Q4taszKA7ZzE5LVVPpenG0GMW0pGedc55+w18Dm9ySAe4uvyoKLsxGQSDwmmE7gazcqkkbjxeE69Sccoy4XfD7Gx98EVrNrXTJG+JlHSwvg+yi5wX+bGUaS8fYM5Fp6acI3ltw1zGiq4yLIyJnpe+PyJA5ICCKeTQfHtWnbAQ6Ft/V6fPvMru6A8v9bZxNKvd6yA8jXj6NyQqO+OMi4+srrUIgm1YES0NhWaJYsIiV0Hfdbe54JZS6kbgQxTZhZsjDKsVMt5NvlmPVfiYy/EmDE9x+xYDQ6p5qfAbrjdNWxWI0t5pM+US4WPKeW+rdIGHPoJPmqlb6DOpE5RwzEVMxjcjsWlqA7IujJ46TxUFnCpmjHqmUcUo1Ei2t/GodiB/98dyTyADfVB6Exn5TViYWQJKf7fNi6
    admin-user: AgCyiUMPj0Zq7nWQsjLv/69mjQP91To8satUgNhATdDpF9VIFeO0vRZBz1wq+YjurGZQKmJ2m0mqZiAL2aWr+Dnyw6wPtgISL2uoykuPgB5iwy0Iv6wx9ZOGGXQ6soAB7X0fUyBDjb22ymgc6bZ06b1bRuT3OdXGkfCsBPXGyPbpNTv5aFYlkpyP8BR7+vwzWaNLmPeXMLFaEaKEPlnv2ydlbbSGnSX6OHMfo/5ERpyOqf4plzuZyItic6CfDj1NqLj6epuqS09YrlvZLHyZNygL3FWKGyFOmaGxBxPsb8z7Ke4MpAXpzPfSzjhFIjBFeYgc7nSOtXtGnHdzkiKQZuUaRI0opFdYnmi151mtL2Vl/0BGckhCYF71dfBjJROP+R5M9BJoi0vBMiQVqn3NUTDbwRni3GZwGvfsuTQjJlNpCFbRd1Cr3x4fxa4WPOIYQem7pGtFpiVzC3909mPIEXmRqw/R6fz1SiNOkn4XupXHMjEV8wbwyqVxVB9Y1DfOmjnD/JzCGfq80qZbk4sEwpVnN7tJGT/+E0T//1UiAe49zCH068vZcvdrVrxS3MiBnj++EN0tYHvr6AMYcGVH+lcSQJCmm3LO6HIt7SigaB045HgllyxNP7VMcwEvoCBWbE0R/gzKyqHswRAhGHoAj65M80pJIhJ5EauqonKmVLe87DOGnXSzOPauOhH6vpDHiHIjR/Irww==
