kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBtXNCMK2uywAv09UhmLpY4mKkZ7jfB/8IQuN3QTWQKbXzi1P0HGS/LUwgBQ43GUJ2mCylvvgneUrmkxWwiObKN4CC/nJwfDcFlnswKazy9/xELmh5WIAF9WIz0qHf6azwgV2rtVzGvoeCdSkDgJjpitQSfMYOH+VMdVIVt6h01DNccQZUKsi+SNXoORhKJ7gsD1xSL/4wLT7dtJaTp3KfdVuSLTHM6ahvgYONoAOVQXyMOW7XxbtKmP6uMpgGSZ/sc/iFe8Wp1PzNcYRSTso3nhU8TkBTunFixSkUrFbCVAcyDrk+kGUxBHCVlIFcuH/lZp3jmoXUTne8EeOGbE8w1CA0Ysf0Sq/9BGMZdqialFjRvkZVRCJ+UPYz5V5HNiRJz56Xq18MptPIxqhOOq76C+wdcYxsUulmaclxVvwksq3+9l2pNScgjc0NZBO4kQZ4dVxwLQir+JP3LHBukmyDquHhw79uK1U/gwdUI3MWUn5fzbx3DuYR1nbJuDVJ6/ZxQXf03Lm892q4gSHp+5m7lGTVzGqOWZhf2V2h6hXv0i1mJraeKaruwGBzHrX+84KQp4yHgaVGqYTIVSnYpHDgNQNZNz5LmErWp8BhmcIZv9mUYmVGWvyfQQ5ftHPJtW5D5bTvfJytPG38Qf+9SimJzgjJv5A7ZobCVMXvj28HGJfT83Awr/ACQjawo7ZBaMDwjd/PG
    admin-user: AgBMIuEWJun/gcZfuw60aZrDBfwvzyNFrr/O5Mn2Lgk8YP6awRJ0wbEfln5fxDsSoN5xRyuD2bJDNvG7belreOTZzWpBonKGiY/aFfJcUzgPzRk1FgbAR2aGi2NIi7c1kQVUy+LZosZj4e6f2L5PHN1ixTwmwJQOeFlG1PCSDOw4EkVhuuPH8p+Gj+uERQoY+7Mg9oplMlwkG0Kk4junpoOCfWRSI+js7ew97NN+0F2nRRPTxGDPMMYkRePstNs5+cXc8nR4pZkTJJbfg1spCDZBOvRejpODEBDBhW+73ruZT9MShZhwli3YtCvJeJ8OWIdebHY1nNFsZJbxgjuSVTpUsufTE7P2C/AyeMkXUCQinWp4to5YVvgKHTwNzMAeQDVGmTIWxcozRZwzga65iw2xg6bhEN3NTL37xzT58a0TRgYpriyBZ46o+8I+4NyWIUDJKlotE38qLZ9TMYoB4gVnOS52OcS6JGFXNhRUAiiPkJTu41alDNSlTgX8gOJRCEzj490ONmZlPnm88Xj0YBWNfSs9UrRHlLvIX+Q4fXx+QiPoxnKYqSnCUzIof/+jWg7b9/2C0ngLsvrOl1woGhU4bK7/LFggkDDUlnil6QuuCayfbIlDdz6BS6J5cgqxzwSYHb96WPUrXzKy9ZKCSuLOeU/317rofg99/MCNf6faQAMFP7jjiR3d9C/IEdQGeI+LqZ3Rqg==
