kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBCoP3FydUVNGbGyDq38tLX9T0nICr6+PPQ8Bzv2HIBb5Ksf9pLlxn/ine7SW+mcCHSCHglCqyOXxbVeBLlCWDrijULX0v+TqVm4XXmBJbOP+eC8OhyVfxRKPWvurXeXBKLDWoDkov5cB0IaGKuhQS1aTKV3XxP/Ptr/LZ0f9QrrDT0Bt9UAAkdMWjHbtFcs7cBAZkoC+idoMp9B6ONcDkD+xF7zhEbkfW6KXwj3loXn/v9vMI5aUnnzHyDUfRFyCV8kWQJHW1KEcVbVWmibLrIjsayBBVWCeHdtPJBbdND9IO6Mz3t4FthtedFYsh3C1hGAjutkjq3ATFCGH+V6odSN3TkwJDr+nX7ZvUKTZLolOtlH2MRlp6XIcfQeA63V/Fd6dx9jZ/kAOXGbjPC8l0mK2U83smIuvKpzKh3kM1JMUF5tZWnbOiyNwM2iYeXBWm0HC3sxtZdzxKsuqLrj4bUF1clQaXy6yxnkt46qrVAVxTPmetg7daLFPUYgydrMyI8IwqElyBce3XPmJzuccBoBud+zBwt4h6B5s2mpR+AjxwIjP7RuuVjU4lnYqymH2oW0+8AGNmhTWFgSSkWJRViQmZLXWi7mzNeoF2Wj6pphTRe8TR0RweE2/mnoHVPy8SW9hQz5dJHu/X+EjImVMj3AePTJ/ouM+2bEq2fH7knVVOH461o05d5jR396pW8eq/u+/jY
    admin-user: AgCB2/I7/cd5DOZjluYHFdKY8EBBncLOjMJiYavXhG+sqsf1KagT8SZMhSkkb7RcBdt9bfEyMlJPnKtITtgzIOtq94xrVX52YTMd7S7dLJchTdJ8K9SSf6YoQV8G7LxJfjg1c8EDDIUhzgHzVvOv8f/NtEoc++6GtBIreqiNsLzEFfmK+N0a67anlUOfopBSN0dWJ4Uv9JG7iXVHUaWnIUZsz3tKz8Ws0pie1/+ybFcpbGg0jZCTxoGRvBzwMXEH1/IjlsQaK1ASVohG5U4nTOLVwWMDO88eb4XuEz86djEilOVTfNPq0xOYzZDIEDoy/Isu4aJdSxqj7YYXDIwMmUIQNIBcHS1xHiCJdCNUUVt96VqRX6Vj4nYHMwhprlJ2nyNt2a6NQik2Q8tzfClrLwz9QS+zJxhlBxLUpPldM/zy+ZUkXrGYETK6RoGYksPyHIAEnZ0Ujw5iFQxMrZJ6gjdxfT9aaUA83PxUW6lacZ8WO31pDNybzEP8JcJoujAX/U+yp8M7UTsUge3tI5hRvg7ruboUo9jC7Sf2oq86Ap1mJNNnVRlkQJyp5UeUUsEVkH6w+DPYCVM/5spRpJgAfIGtwRPDsQASgZiov2CTG9eC1uGnHabVVxRBb3MXBoJQ0O5AT7NnR++VmmyH44VPAS50vz7xTfxaQzctUe1GiQfkhfTKVoBMTqJH1tQltD0EH53e2JSjxg==
