kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgC0W1kBMLp0nXF3WUayZyvHpZ+z16fXhHdtLSy1NQRrR5j/Bc7NI52JyoTOfbZt0Q5D25RKXqAjJlUZ/wGxWQCoiZsL7C9fJ8jB8ZPc/LOiDEwIGH+XNKrki2LdZXEHd2PhavN3z+OxNWKuF036arr3Tqx7kVCFQza8S5kGkK0zWEg1loQKBXGsTLfbcBodyyRDm0Y4L9lNZkzTG+hrY7NAqVkyaVM/653FfbRZUVN+kxf7NZmHWuNTwky4pzXdSPOA0JoCUVnhRyn3dfND5UKAaKnFCrxUvRFvNfC1rZFMdHUzGptxBO0IBbnRKzKiOhk17wOLM5slgOqwM+BJFxMBvUVvQoPMG1X9SEWWhLRgRISBXWlkoC55mSfMc/8hA98g5gOQPN0WBClEkfaegb2jPNz2D6jYiTpst3AUmNC7ZF/F8NJ58OxK2+9AQqzyvOUCq6l8ngvOaCt2WYwEqGEPiAV0auoGQE1SSjb1lMneGUcSmIj5kCsB2S2n7I97b1vLvSzQmm2txQ9iR1dBT12TcfJJp11/bLeij5l3a9nzXogOKn1T3021aqIQSQjfMLotyvDyupT5GOCjw0IGwBz4tYVGV01gCT2vWY9rjc1/qhl/xjMpsTG2XkI/WUF57YCrvLuDNPMsddP5nSv3R6FAropmJV45zujV5J9q8hGTulMK3lazyaafHaIHCLJau/v/ymcJ
    admin-user: AgA7nwdvvxcEsipJiQqMUPO0fOxHEisGpId7B7kiuhaFjOJOG4Vb0woV3kLBH4+r8Ol6+4cR5aGTpqXE/AfiVx+dicGZ1RsD8BBvm+mXQjM2dTd/FFOxwSD/iJiqB5g+4rzK/nYV8+61PDwe/geIT4naSdyOUNV3ZhJlcKsgNrdU+ePQjqE4/J4FfZE+agdlFYkM7J89O0TGtzrJXE3sqk4MHOkGviTUzrXxxTiNzb5GM7RPyDKeGo2+K9/940OY7LvDcsko4OnJdqnjblDcOcKYjBOAyzSuDrgV8wPJ7buOHxoXsYOzAp8U4fHi6nsIt0tEZh0oDGbzLTmfGejb1H7pNTHU7AzVcB6/SVSmIz/T7u73Q73x0xuQaKFxFKjGvU+9XvcwsUiQQXGTOJnsz/cEabxdZJbPJbtUMj0wnH1EVVyx9ML6uV9czTA3gRUuCkObdqvrEYVzYhlSBuUiWs5gPXWVBRY+FhHDCkdQqGfZVUIblrkyciW7oSss7Q+ie7IWdco9FzehSSrnI0MUrNZdaqBxz3UEyJ594l+B4JuHlmzuUJdTKxR9flAjTPRjyH2mkn6SLOUATJiXHZsneA81mwXOgEkiQ86GzVYnV82kRHOdfdTgV4g+oyKhK68ATbYvyMbHMYHYuQhm0gvdwsLYLwZVdnHq2zpT1V1nq0CFHHLmaqMmDxb9zGhDJZV2WEFUsci5
