kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBBT8u+kxIbn2b8+uYmmPwMYRDrvka2GThqb8OHLsB3SelqVX7U2wqjmdXAVeMApOGC6XTGrpYlDaPvHlS1fEUGVIOduRLjfJqMUWzI08swhobiXf9LjynmNqjAcO5Dpl9WKB8zzjA9mIQXBytyE+luqOP1DUrkDHs3FW/YKfFcfOkDMMAE8JL3y94ohxYsSVRjEV7haUaY1ieT5fld3HCNIRMupHBg0EYUpgOQqovDRj/mAyYSvGRwzEFGT43EiZRlfCdF6OiQ2U3Kp0b++3zp/+H7LuQQ+YpOiVCtJhhk4XwClfVC/fX/AZmKDvVf6GnbwlgKw1B6pAf3rfl3xUuG66/feouzdMNT2+gBhUqhnShtOGzU0yNJq6YQT7dGnWo7chPlBv9IVD9vdi/V8dk77xlkDx5p/AfRglKRpPugtYiDnpetm17kehrKXLFiE0DjymxeEUTarY2b5/cAdlN1fjaUQH+CatL4AAG+a+GLkRxj0A5qx62TVGQcvWyztSVD6DRCglSwk01bTzqj7RcpbBErj3trLx/AhzQAt4/4ngfFf8cqDd0acvqPgkuKAVqj8ob9VwSzEhIvIZ7PAnfIaHTeDvHqjbIKFlRSfawlLbVs8z0Pl+8k+aYx0HHLUZoGnjDr4vSMByDArnXpWyVEc34b9LbyXblGJ+AKBIFrrVvExFezEwj+KKCen2QFKzyBEurc
    admin-user: AgCIS4Bz6rjtdgt7fDE2vvOQd4dTHTAyTLi+hCL2UL5FVX6kbcVRiTC54/3qbxL5RA3bgruoAKt67MEV2LYQ2D2vvRnowi05kHNJZ62oOs41M0R4BaeRsPqvexz7SBElYqbBYTzQoJ7V3cBz1QmIdPWrbD/vM+ekM3Dy/Gi7+M38BRuoDT4eO40sUb76CImOFiF4mvIsFxRMRg/UaZc6CVTDeEIObMxd2iGyqzDEX+uuDUCRiFLTdZtAsGPWh/OT1eja9u/H3u0LwQAbikW+zbT6CuYJqsBZvtRP7NGd2Ac29nfoFakCKCRvvAmxrTWwqFY4eNHRzIjxKEDkNcBBsk9qxTTg4iENX1UY4Q+hT210pCEIhpkXhE6uKHKC0HrDajC0ylMeTNqsvXzpugx0EM1ZrIQ/2pv0itS5vwt9x0+Q/A9qrLN27/fbQteD7QiU8I68Hy+Q0qgTeh6ISIU7FHEs5NTMZ4jz8hLZkzb9Fy39/M1A0lzRhcS0X4rWnHltfb2zLHOe0WbR0F2r+0+mf/Pj3HbhClwgSUIfBFREEp5K89LwJkZ4XP3sNOnJlHjxyzOv78/+FiDjgudDptDMzTdbPloXR2nmUAkCMx9RQITJGxGge1L2Gm+Dr6hMxqM0SqlSsGF89XlQOGcRnUJ3vvmLvDZhYjxrtwT4Apn5h05F1c6CzBxvWytLumrNQ0KG5wFAg4xvyw==
