kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAMOhpH4Jk1Kbpdqn0YFLldli72gA/U0OBBPYT4sTIxNQLQzIvD2ItzghhkOmEd3J4vRHr+mjvPR55wWlQWsKzGDjla0kxdsdZD30RVZT4BAhByO9XrpiHBG6RwwVsYRn6ysAdS1OqBRSkF30do2w5xilWUP0pPgBzN7nVh9449ojH9JaUywGWmaZkiiTYlo4/IReGoUD77w3ZnEaWFfSpRe7W0Qc9iK+PBQHCYs/FBXEDMBJs7xdQkIBeWVAMO8jdlPHO5VWmJKMqXxc7fP0M3wRqTV7k+PNF9VHWoj4loB7L6YAngwOvKt+hdhvPoIDPolwWqvwW24t0cj0vfs60j9lZg9xpIcnvCrUKkDu/qDZJi4hzfwgU7RinGYtALw0uk+AaN+I3gUV71Wq6N6xcFXvCOcJQhkMn5xDKlMznZgkj3nTzA9DzQjUoDrZJtww0gyCzPqn/4pwxMO7jaYctWAj0Hmah7Kd3zfwnnZWS1qnOv5pQmdeQ5BWF6W4iIDXnwOWhm8zuQ/CjyDnr+UWJ+FkN0n4iVA9bVVtUdWel4+qjO8Ov1y+mxzjXhMlb9iQgp8WiuBQeAKuJH+226bmh0nuAhEDkwY/R1ubyDUQo7+CT26vlpeijMBMcXF6qytTi2Z7lVKZj9THKlyRCEjOM/852OQlm3zqbiiyTuocfB2B9MBm5Wo/mEEZquA9yLMy22IUuq
    admin-user: AgCN3xj59pG4/HSMHSWfaLrOq8RZThgAs3MZmb6HPDvYMPvHdyw2jbpSVSHzQCsytcFdws9Sr/u1Zw0W69bBtkVK3MXvKGgoD9U4Q1D2TUQDta0pv/avVUqQYEAyvJpUz88xfWRLkvCxF8x0xEdj6LFeWbUsRjcuYfephC3QiL3P44fW+D4EDoK21NaHis2yV1kDoEj6Fk/7j4b09VgLkpspRZx4scoAcrm9FNcUiybEvfPufSqyW0GtS9Fh2yLXG94mjoaJqz9hYdHcQpz/4XmmuSHguJqscDdJehg8HIu274oIIzBzdte0i4cMeKDHJlJgRmMZsKbfiKU5FBtRtRR1U0NGxmJtUQWlX8QY2xtBDWvvf8PlbCDmMSu3E53jTC2b+W7B2WkS+UMLBryR7L2NkQKj2ZUtDFwM3nziTZxCCwD3mVN5MLr7UKvELehCFMPWaVLBc/h0XNqlUlDm128+it8KDWhVcgoYj8XOmsFNrcnCd75EcTVB4zrbSXQfSrOZj6B1Suupa8sgTYdndcMVUWTBhT+C2R8Ta4DJ8bUTDLw8bJdr+kKclsaNUEYrsnbbYYguvo5XLQhPQLVvR1RGg7BjdFpeaE5bAHhnvlD0kDzU45Phv6kJBD5OBDJXP7lJBiQR4g6j3nSABy2wQxDGnsKZYq9WHr8q3crvVu8qAXlYOYQ4w5eBtmevUCJNfdQ07Ru8+w==
