kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBH8ajVi2gRZrqOwe46RsZLJFVV9c8ADFy7N2/Y9thQ89fB/PaMnsBAhYUD8dMv21qS+VYn+ZK/UylQkzcUzTB5TLRv+zfbiVSRuKbzGHkYOWWf3nZYdGfvZVmOIM4erSXDjN7cc0UGeh7XIQLXACvF4gLkNUxhhoOcecObs6TdUnoX+TOu4ZJCxrS+d45DscPFa63NC2FZs4s6sazHcXXJnD81Y3hP717EXWkfj3PBljyW+sqeoa+LXkWGsabeXuepUgznpvOgvr133egDMfeGwpyz5WG3PT6uBfqSsnRrnfpAhRZsMvKquRxH7EXWPt4waioEJfQZUDoF2oDhUoG7tEw67cUdFCgZ/AuBBApBn7z4WEuqkjsCE+iFarfu/jdgiBs+xNyFRHVbbpffnr6sdcTKfXL24Ee7HfmqMp/GkCN3HI9/go51Uku5YROIudQtOVRMjU8/RPOE0OogE+6+GlsFQ3CrA8ab5UVZELambmV4z41vOPFzyqahIRcTmoceNysIua9ENz9B7MJPZQHPJesz4LIAEg0T0wt4P1Hyxsp4LVEac7DPnM9DOUxSPPtEKxsOygvmLNL29CQKuyeTM1PtDaNAFoUzVmeEMmF0jAIrK2zPAHQOCpBpJtfSIMNB894CKu4n5LI6ltHxmoZfG+ASeDX8UqZAFBD4SvbEcl4YKWdutPEFBMOa3Kg86R/s2koP
    admin-user: AgBKCqQifD1POmHh1dvDL7YqKa692OpF4NlV6RPIpBWyXKNFSsJCEfFTiorSwoA0FtvEdJr6qOAADSHnjSRcC14PGMa91/e2aFTLBkO2gItB4wmie8UR96ERcfy/LynKIWxxaeScan0MLhkc2cjz29m5RRc19cZ1M36L30uJA9PTFv+7sC2/saBPU6bDmEmr5LWoHmDRA0hwVjtZTWx3ZTR973D2Lo8jCpFMLmkmaRyOHTArY9VS8GEhbuz3ZDncHyIjCa8o536uztXwuFAh1+Hi+eq1zX2KDxEK229PN73Xq+bf19BxTN6bJucDG33BEQ2zBuVt/VSnCRmU8g0MdUXSCUBzItI9dEMveeoFnCTkzenUgKpIdiPcTdpimhWX68KNBiafGFRoBGoA5rHfIup/tzitaP91ibzCnVOcnfmR+lerEKaDO8NHfygPVjPnVuV6pgEx0FSsyfh8K5Sm0aaqZluQ88u10CtdvNBMJyrmC9H7J/0Y9xnpGmJCBowQoikEk1vgJ4hgkLfBF/MTz4b8NNsJgaBxLGIyONdgrdqpClfJLNoOgxx57TcrM7cIV62IZYJNs2sJMz9zJqbmt5Pg0FY2KC0lkVEzIfVT3w4YyTVUwVRD2frQH7usbqw+iy3QidXIcmKJNar+AbgvYhQWFMqd0Q7hlSKvtIzJAcvettj5bzjjJTZUxDAoxZ8l9uoyqRSszQ==
