kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAIInOr0YUPd1TWj9jffD/tb4s8WltX3whbmH8R9y03q2P5JqikDwHPJK/wdwtekdFYQuGsjjz1rL4s07f6yVWo41CoixmEDNPOx2756t3H2zGJk9BmHyr6hzcA/EtWx5GLCFpqUBceaauR1sOa6bKC3RSI2BYkJh94r/EQWDh9XVrMLtCH+VC0kHnUJmcWMaG4UTfXCfGUlf+cg3xNHG2N8p3reP7nKRIjQnKTkZUPmhZFy4fW8Mcd9W6TUo9EWucRzCdAh7IzQrg51AEsbjhZFKx6OsbOQy8BneO3KeKnj6xIVE5bVOYkVwM2OKUYF5d09qtf9AzoFd8Dj4g7XC87J+zz4f0Bj5B8q34OqpX2VtLaxgnn2qFnZc1hdYrB3TLnOg2xqJRQuiYAA+4/u46rMlFu9DBdzCDRis7PC81vliRGs2yTepEHc0Pzqqw9T1SwHWTRcR8FyKQ49HbnRHNWZhDb0G0HLXYQdxs7aZx/eE2d8ozoRS20lUqmDCK0j04b0EABG6c7zinN10Bgrc4dPMTfWyDGfySTXVfPsO4vPYr75HiC38QnaGcTC/TtBiVONamo55CLad87WPzpqkhhWu3msqbMVvZ4pMlGFYHXKZIWURB7Tl8BGdw9k/eM60au4hOTGeOo4eIlEel8gUhpg5sjq54YSTzaKhXjagubNlo4MCkaQ5yHDyZ36XbTrCKaO2zm
    admin-user: AgAHzJOAfzjY8gIIS4ono6d32L6dA/JGLp/NQGWhe6z5VGEc1i7QG/vkYzJ3EDxN/gwDYvpO3ILzRTUENyay0UT+yWVwkYr4oERxcE2JaX26q24n7g3zcQyWZf68zAlKq9Ye1spUO2qUgi17NEM5sIzDvhsVuuWjDk7wLWPMb70mRRQTEnm4zJL9/03k0Dh+HUn8RVPXRGU1pkSR398/2CK0Q78RvfVcbMvdJAbIuIcAoJM1aJEU8ZTbuio2gQUy2x9arhcRxhczHhGCbChMKy2/qe/lLkaoj7sOyWKMzCexsEyt8oQmn2QR6SqzlyUazB/N7yCLaJlARYvREEN7xFxGaQrLytiwmquFrYKOK2hBi2ZtNcHmUY7/egfa6euJyDF5tlLZJzVxPcZDS9YI6zRrX36hql7An/MCFBa46g8+344LFubZZKz8yNVnrPueNPQcMulEls4nPZnlfatnzPnby0uF6SyKtFUCF8JCnj3tml6M0q/5/Sl0jYKPVEREFrsVJQLQfAN69BELBqvO1TMLo54mzAyHurIF8vPA9NAK4yvE7FXBx4PfJwYQEKggYpfAioHTNYqMDjw2ya/rYY57Ev57dWhHM59jDHrpVbZVsdHA8tEJxyBsDTl+90mTYDyCNyMOauvhUojGacXbjKorH5pgQ6GOY8pm0BRBnYpBgeOPYaW6hAwPexvmAyYHkHfE7BFs8g==
