kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB9t/FrC10icJy6o+1+buhcojyKTr0f5sUEmTsq0vWdF7/LUH02BtxNjRgbOwJ/wKpzb9mTYczPCWAsGcvXkPPYrIlRGgyWO0Hmyfr9mVMwVmSwGqB8JCloLcMJh9Sl3PrAkvAOfoZwMtf1pItG2RymEIeTiY0FYy52C2YnUCeFyA1jXV2aRufCx494JsrQioa1bQ4fd0CpVpP9EXGqhPsV0JGA3ZW6pDiuTFg6fF/HThf/uZkin/Gj+39IZgTLjvNJgNuo7NotDuq4obVzY0akt1lEQ4JYBYcgfDkfddzItGmeDbjEi8YdgXOJEyv9srXv8byw6Hwgp8FRQ1EiTZsqYQhClleCNioUoyzlaxjDmhLpcim0b/qffkm5pkYcuztOFD608Fv3bW/uXUj3lYtN4xJD6VJbK20vEWesFBcB8NR7FBEwl6MGZ8KT49yn3hNkK3hRs07NgNg1c1BscfOi8sxBn8Ol8lGLUc88163xtY39Nza1Jh6Em6zmWydDBK4T9BskWGAQRXCcLxaDzXOk1Xd4Sw6EJJreJEm2SxtmTxUAQILWDigpAIwFf8hCC/DQ2hx4nKuliJJQyMj2V9Op8FvYm5rBelnUVBPactL25TPcDaq6HK8/EZS+YPUMqfZcF3PBawLl6ES11fgOoKiibvKq1clO34A9Ovk8p6ZQ8sWMtn/cHvPJL21uEYZDoTiiMd5y
    admin-user: AgBFnfJVXOX0Z/vqppfQ2G8ftkwjTwg5ognABd0NwTpf7J67dZl1AQGZtp2K/vPUySJ8vqyCHDIOLCIR3ND6dGzjA2s5z85R8LPjUvDtQM742D0xyAO4zZx0XuToHv2lE9E0Y6dMFK1yjglFA+oHZYldazaEIth4dUXyIuRaxha5fuboWpCmG3iy82mt+8Foz8RzLxLY1d+0n9qlvu9om0SEIznVjzxg8m8Z6kiuud0MfXA1Flsamr2xceLdYi41r0hJpaAMKNhaPoYkvVFxV1r+yr2zKxlTcoIYy/ToZ0k4unLepZqlW6UYZest3vxY2oq8l26ezNOJpsygMLpQeb0zelAKeeXzA1AzBBbAYQYUOXuq1u87OMPR2dt5vJcLufF5pw6VsWMs+gEeK5u7OJSGuXUQ2YXFn8XtXr67hkvJRyfIdi4AK2vHZ7GXTqdlkOmIi+KTUWwvH5BNyYoWuOBMxJRNPvjH6q1S4D+Pspv85eTLiT3GS+ZdVOWaFziXha9ef9N48QmNJuO4bdCC5TqyLViVp67hmQ9voS1sY0MgknMRZM3JbYY4Mk1as3iHutDZsLBRPbhPry52oBh+UyuQDSjVW0AusaFSkgHIKYMi/SwwTVCMlYUgPFL4bUjn/rXMu1d1uc7HbpMiyt8R16pXEecX9rhwqPX1zMMDEVHZYTVPWy5ZF/sCC6RA+E4e5vjumD7AsQ==
