kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAt3uR3ix4dfdqlCTjaRZvyKBcgbq7Ij1zl2L8i0Tp7ofpGdLDVNusS0KVj0eu7HL9RmgWr23zjsl6iZK/tEUQoqaobZRqjUNwrRcObF+MGlKYme93X1YPT3b1DXNmHBsvDfUeHsVRM9cGgrS8V5RFo3RDt7CUnsZsMzq4NjsG/UXkZbyK9pa3xPVGe2E19Eiy6EYC0skGs51D3486cU4UUIf1/JcHshI6o+ksG8mE4sc3duhCLqrX7HbnJ16itrOAtkKpbkEvkwcD+9QfBkFgsNjc7ruPqcrPpDrwYfBz8WnYVh1/I1L/YzHdSyc5UjdzdciDqyjviAEeTaiTfJTRxAFb6sCw+OFzNyr3N12Q7Kl4FwyFvA0Uad022JvF24nVI/9zsMlqp9Lhy3f2Ob9I1/QxF/5wyGm15yltXSfa5mQzZQP1OfC3yBCIIIRR8HO3liE7UdRKCj85F33jjsVD8XsVLVynF9BFBwyiVG9yz1z15th/P71DXIvqNExrC1e2UIrtWl54Q3nSArvPDY+QloHqiPXK+n8GETYC+DI6xVlEPzdxuAl/5Gx0C6zy4d3h4s9qYpJ0Q3Uc+R4itnvUB9C3FX3BkHeAsJj9Ijyska41HsWYBbx+44Py6vuu7JSPsvx+mvQ7L7Olh6sXyf1m08IyI60B/vChZbSVbC8dSIPRQWTMuNd2g/AZmpHzZnIAVqqdV
    admin-user: AgBzB2BRNG14vlWVgXfDiRxaFXgsEQfUDhX60QARrtYVjNchN22O/brgtwSM2BvvJuhBTxfa/uu901wJ0c/EmpQRUjR9AtAxRtfzmrbDWp8PwJFjuLFZrbQGOwxzfci6QNRuo2yykh0rpz46c0ChdxB13T+tWg3bzI/Ikf2vdPnqk799QK9tCiYvP8jYKii/Pyl2ucbOw2MlEg5Ila0lTFi71gLVGWo0vZmBpSJl1ZEiIKAs198aaGKFSmx54DmBu7UOs46LMM4l0PsP+Micb6M4C/OV8xU/re/gV3nUtuog+wh12gkoMgWGngqDxO1imMCt2ouRCRv9+MMR2pkqE4VOlhcII8WZtZeEmiT09Sd3Ci18IH/7l0rrTIAP6eNQ7iu+uMEajzUWn4Q1TpqBVtonGzMM5sfK2exWadgMNhjQcaFXgskZgjG9rO27hjpTFyEXGwDq/1F7dPUsBej067knRHFENJw8RZXDWGkbY1yuLnZS1bRLkvIOJiYdUI83lzML2S0fwc4YDr0p/EX8oNWCvUmZ01/SaULi4m/n9XYz+VY891z1VuVi7220smKlSbd3h8hwa6NTAJJRjsI5q9dIMMUAMhLY2nkOJ2ze/7R793Hdl345CtYHY/Vy0xld5e0fMv1gq2Cz4VOCdo3BqAcXmCI6yDU1GJhjjRyyHW8AD+Ean2QzyYHLjkiylx/62585cX9Y
