kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBaxG7rqjwtUQFSYOIpzZ4+4hrCKTlpdbAl4lU6FSZuycx13MNeCJ8PVyoBwOXb2rn4Wzv9+MpJmXt1+5rVtZI8WO2NnwgeAFIM0UKoG8WOVrQTxGWnYDZKNotw1KqQVKgIBooEafzOEkU94S1bPiRx/Llzk1NH8gfGDMQ24MxRD/C8prWJflkwDyYwMVPRdfpMb/SF6KYwVA6B8tXLS05BHIuP1H1WwQQWO0d35R5IBFHri3S0o+3uDfvvAqw3YufKd9J21xkNVKgOgTk5q3V0kND0zQly7mpI9cBoHh+r2Ik6/CbOUwph56odP54FGWIi2LezMm0Qp4tflh7BT9aRyM9zkzZvEA0n+wQwOoWCbR3DkhoFYv9Omcu1xoi/C/rvIOTtMgYJvtYYvydy0U398HizwKQROTIIf61agA+0JAOpjsLi1FkIqLwOLtKTrYgIYRlsBnozL2efSLlXHwvwT2FQNtR23McI0yRh8YOHsyjD4n71/vasyhvwyFDggCEtyNBI0/nfjFAKPjs15IegerM2rvg8ttrM4BrUaOdqxwVdDW3e47dIVJsays1Cxm8T5UBwfqwPQFGDVAtGOAXJQsaPUPZsS30MVaWhMphR3/ZD+2Fgzty+/Mx0BFIylAMhUbplk9xIsPWihC5sFwuDvPbiraCRFWkppVCCKBfyDUSmZ3SI9uGnPCWniiPSo8VlyXdH
    admin-user: AgA/ZlFJVRjRiQp3KA0Tmm5TQWLTUa4LpV5rZ1b57WPF7m1iXMVfwyDNOVTPdacgg7JIf180sMu5EEomg7wYAJwWvg6q4j86hR9evEDeNtUZd+cmaaXquKxNp52kcSJWXV4ijQUxHZ+3k3PrLSNx6cosFjP9ofJZlvUgABiNTIvtI5Zsu962u+5T3e9jKvg+UOBUzd10SNnrKl0yR6gu/0vyOiDclDiKiU1+JfPp7hJYqyOumyZC4QQf/1OViZJMJEIh08tlsy5T4+Nfwq77sEBPsuJa3QnUH/4G6KyvzRTI0NA/rbSbPz9KrN12yCJZQ3Lu4gZVHWcgbwnpDDMEUPE/i9XRCxqnZDowRrr0BLeDbQoVY5YlQVYXu1jJt+3PNYAmF2XN7Pkm6V/307+UV19xafLRSXOWp3ofQCB/hS9F+ASIzRtz8nVZqdbL66Z7YpWghtJgErYIs0yOHE/trm1ZK8ENDvTV+7YiuZO1cvhmGyapxu4xi74z+gO0hVCSHjdPXqVsYkTsZ1G37pLgzPf/TG0OGfLHNNcMXtJ1adeYezdcFJN3UuCmcJkSdciQjvm09lXOYvQuVwFihSTm1S/M9WR7I6/xDP85RoiHBHLEed3e/CMNgn1R2P1uFpn1/Sbk6zgJ0v1CX9C+xszqSof6igzomloaurBZpBhI0TWgQ9i9g2TKJD4wgZHD3wLloP4ML+Se3A==
