kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgC4MfPj21XAXTkIEynLpc2bc+8Pp2Jnea4eufUk0TEOcd51YY1l0KwtVwHS+8YR+et0ElNf4q6Z0F/tFR2ebNAVdpA7qvfi/2J8niNhFMgsSB98PRtdRregPkQa6zJuioMXFjssfDBZyuXD1xpeDZdY2BwZ8LQTMfxjg+ygIMKGTPoN3d9oZ1HKo5wnQFLZUVWjsuW/Sol/BXebGnnqp9QwhCmD9hAefAFn2EZhQBtoDm/BagMXNAP/FOK5zvXXwAb4sZY0WqW46CZR3hGh77TFAVYLErhJ+RjYxcHYZ7z3DIuGC6y2DN9cLwjrCvdo0Bfxgv0oUDFDlJqYWZhxlzmqhomTJMkNRfKRirrrBNEBEXfiQMbNeI565Z0ESFYsanFfULmbtClLhW/paBmAxOX/qnVgL3NU7BwVy9zt9CMxm6cG31jjRU86I5O25fm6O95fv7EZExPjbxjDR4FMIMaefN86nF0AA+EZYQjtF0RfFQZgFuqP6QxgnfGnjnCY37Xp2L/N9xh4vq+iF8G9Rhi8x89qgkt/WLuCLdXq5P85vSOrFJb+HppakJupysojZAX6LI8NR9OpFb1eJgZrAk0K7jhs3WBalg+tpAk8/ON/phju31pJCZOIBDTLlrDS1ryFPF+aSuOzeRxOlUDwp3V1DEk3IH5ripAdnZyfeEgI5kzbYYq3+dxPL9Xd+E/gJkk8cHwX
    admin-user: AgB+dFf8YkXWra2Fte2JzQEx0IBwtRm3R0sXxBpxwa/vRhkfsJQuTCk45io23JbRLjBeC1adcjZEV3fHyvNPyZYPO2PMbUimns6nsG6aihQSY5wRjxbtY0jWkYW9ujdvPIoGtEv9OxsmP9DPHB1p+9O/2ey3YkkvlEIjVhcAm+Yx1KSeOlLd0uMJfkb9WfYcNqdDEEKOEaa9fl2JGZIB99v6nWZ8j1/RKSmwmbBscKvZeU76ooxVCq7udtAon2+QsENt1z5Ug79iApAAYu5BQBzcbecVpFArUxxn1N3QObVoQaF5LCpuIYmzNIhInZZmzFHXtLG0/1FejcP7yMD4Jk1MtYSCAopJgnRHe4Rmd9umWTxFsFgwy8szeC2W8Ixh/yNVlfFDEC/gihdV8XzeteEhkIWfMvMFM+8nN5nc70xSQKWch3RUSVg5vgsewtek2uZ/G5WzOabaoyh8PfFFPZC7vZ3zO64zOTe8bt00lN39dXtWebcLwjrwMthraUyWYmGTykZjFXqzwbb5DF8IKQHTX6J8vHyEqYSR7UKsPOVDLF+ZFG5UbJtXeNJsKy4Ym2v5KPQhqT3EPVbpWXhNoby9Q2u83N0Ycp7RQK7ZbSek3Y95l6OmXB3z0Jw3XWrs/WENbBxs8LhwdItdrDgyvV/peZQq0nJwJqMjfiSPUmD0W8U8di1Gh4xCJ/ZsHtm7nJtbfvxl0g==
