kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCu/0YezR18u6mktTcbbazEiYb4qPgHoayZM6N7IXNbp+eMhq8k4aGGTHDYbP5xK0gtMCwFn/w7UG1s3T2iZbS7L9Dvr46mtyPdMg3A6MLs1F8QHDvRqs4RbGJBl2bl8FEHHXEqNNCA2/uU2hI95yNIeCwEKKwCLI9aGzaX41kJLt2PwMegZeKSf2LSsx8bmRruCQY/xV+ZPFyZ52yOsPoe424YDt+o5n9PjjR79sF/07xAGcS8x0j8XQMFXdbFtASI+277rYsyXne4+03naLeFy2vPNrgEpg+kdVc2FkO0RQ14EPKQSyQoBP7L4taYMhungjl3A38MjI1ruh77bxNwEnm0PZQtIH2sTNZHVre9eGleptuD1ZNHiDfGgA9chi5uMEjpiSaX/A5WkdhY16BnDXkVTTrrLcLTXZhh0r8+xNT6BeVLkunFLjNsS/3M+XgKzquiPSTpC65PkfpZwLAX7JUt6a1LgE+bL75zEQR3LOMYlzm6VVz2zAWgitb2CBqBlWdYldFIkEpf9zJ+0vE0vq9SWUnuH+YQTPKeeVlnuXpz+96E826o9wJlf1RWDPszwbfk8EZIphS2UFm+UfVNK7C3N2a9+svrEpqRr6mmlzdyARNxrLFkvnR7SoNqY0/TYLiRqRZe9wVnPi3dkcA7ICEHdCFgxU2JMfW9Io+fQMCzGA+C/buQ2FvNDNO0L8u4GF8L
    admin-user: AgCH02syq4DcEPftfnr/Mc9gEfhD0/qHd2N92kVND3zNMbqLGNNZ6k3B1XVMKmzwUwpS5K02mxGcUD+U2UtOrFI35K8ZuEJxNrePcnYkwHpvY7Rb5R/Q2KuLvWosRyMs3LPlLwX1VoHQiOADoARen9YeBP5PTpwgBCLVpmWJmlTpPTs8j28Isq1zPbYZpifmx7+FlqGQSrnepvsfpHX6lyKzdo6BM2mlSKGaTvODbQrfAEh/vOW3IGieaiX4dzlgdi09WnbYZX3yWAJK5KCdqxM0Hwo5B93ORe6nqL9OKlI+2OFbdihzGnLSrI7n/fmkM2WRoxI3dHgkVVDXrL7LkNjLesaFpln8SDxrcSwZvw3g6qbB15VvF6dPUSAsmX61f405r2cUV+n//jtcPCbSNYBX9n1v/E6LDHQNbnwxqW24zxe0qLz7z9ymAPqLE+5ubixU+nNLOk+kBaDHtewH3uRRh1jj0mD7pD+q2Bsy0Dnzcw6AWZwdAd0mx+JdQEUA3GFM9oEqC0muXUqIQorJC77KAiimRvIb+S604Bnpiqibk3/lHdbEiX0C7p4P8zIbsy3pChB/dWkbXYT2rp+gJkuBgBvnfyz2MDR2mKL2uMtyPy0fS7mkxWQtMFqjEFt4fbrPYHbD9tIR9s2/Nx6ZZ97S0ApV9v4uHRRKvj9q3GM2N4dqlRXJw47q0qNN4H6GJb/s7IcoZg==
