kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCrkYp9OFFV/YnGrnazDcOj8eSf9hI7vJBQH7MDocrqGZKxUImHKx7PsveoJ8JP8CW/vSUBOPu6HT8Gm0gAp7VFfg33gI9lf3auQpTutW6gSF6oWXWCO0Y3Wz+xF9w9jQdtWdIemDsOMgh79+EhfcvvOy4RnKISstI8lXTkCpagfysEm7eD6MHbZ1CNMQR67DbUp4MzfTfEkDK56x2FZ38WHa08/8W6Zs5AtsTULQKLdSrI82YQaEarRPcJwWKfDzkPjxfv0KbuBWXZuEkE2v8sGcYjdbdGy8M8Hhpg+k6AtRpzQCLKrtFhhe2ozQzhgGLlhu63jdvXwHrraxdcJGYPhAQ9+Q6kn1IA/Et1cxJZ34QmuDWx/aimro4ssr5zb1BbCw3MBN7zr6h72EEYmSzLbQf3ZH6e5QuRtQKVmoR51XQGwD51TDVzSIIQ++BHf65aaIc2U8xpYxkq14BRMGBsmd8NCfyWZPh7RSIOgD7kjWcTcfmmLJjQOtrOxcfM4UAxwdLMoCA6WNIf07NFYxq8kx7j50Y7rmfzE3wdFm6tV8YHHOMOeEsuJNHyJsIkDdSDDWsNPRSFgwtUSKa8OwE8efEK8ElmUi2IbBMjQu5tXH542Mzc4PBo4++W+q9rhU7LKJErdQ7NhHLDnVejl+oJlXp8u+uO3ka4mEeBx0tvw2lUaKkCpV0BvQyb4vDf6Lg8G69R
    admin-user: AgDCXuER4VUIsjdXY1D4hGPt8+HObj2qNojJt3dqkn75eK2KEXlaBWHjv5lxEiilgplUC/t+ICOao9BUPZJoOt3ZPl6F9+m8VTRef0H5ScrFmyzybZ/K12eXq/u9aeZeqvZ0hrER3/Cnm45MGG/lUxcEWmfjoHB+xNsUw7PMK0pQScdUXfpxJfUzeyMy3dT4Aj+sGS01wersJV6gUPe+F0HXHZGWtteyMKwQUPIPLyqcJK78Zm/aDTNFSUgblV2Cz1EUxBcKTQIJbOfRDfScwlOq4YLUqdYbFARQiYObZp6barFTL/9s6sbqopxbQtO0Of8nMDrfTcSE2MPGX5G2o0QjbMYBQg8JrJl/8Ir7Y7wcBMr7d00nCIN7vgCsY7bFjQhw6PpEdKZtH72YS+XhMdkGk5qlST5p/EMoQz9jFA7PZUWdQ7fRAxBHGjrX280mIqNMV5cacGik0SniWW4wTxyv06IyWkHY47X510Ly1kiWSEeDGEDd70wqypWQ9xavVgrqp/wc7GrLdAJcBqEdW0lScA3G04TXYEBgX3U+sqV1afSQZP73WnNIGo/jgq+7uAbmLoKX6eVN1fEQ8rW7XW82rbEMZvUoeCwbUi+xS+/D69gcfYPHURg6sCDDOqlK51lvkRHW7j+qEg2dDGUpFnPjC8Y3ZzlmOgsHRmDlQC44b7lrnbAbFxgTR9O553lDXvsLPTw6jQ==
