kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAUa3jgWfk0Z/rsjQDCdWDp6e7pJdVqXCqNhIiDeLc1OGEXa2EmlZeTT2c87weeGIJa305dVBaNssaDkO3QP8Oo+y9A3nbGTJChWIokT1VguT2mhEABr5ZH40CoL1c7VxZPKaS+zFJt2ylf5NC00Sdos01n/K7GIfOuYxl5od+HnWOhJbziFqHqLUb2FEp/0OmxXC4UYzqRpWj/S1itdzleKAuVcQ2F2NjMSm8hsDmiGQRSBX3y/kgCfIpPG9K9S99JCh+umvCqxhXKNeFyTjUfFlqhOpeEG15vN4cfFWzQZ+gspVvj4w8jSdvuuS35/Q/7Pb40R1zH9yN1lnyh/nhPp2r4gazkJBU4d1SXLfMztG9NONpS9joToP20bo1HyD9jHED0P4eSacqGJaQutwY61xlq6TClneTfGq9F5G0CvD89yrbq/F+wnsLB3eVhUSsHexTFtA+uHLapvDNIrwf9UMY21pR+OuPcNRub1ZxHgjcEw/uQzuI4lBHnko2TtK66dkbFrGYzNn8nVx5BeIGWsMmaY51/8rHw06+pkCWvpZT5/kv+jezPwZ+PGdVOmi00LjXtN5B7ufK+p5BG4gPGoggzFJQzJ/kn5Z5o5bZGaxTlLRig0nC3GdbifJaes8cT7J7kfRT4I7jfFK26IdFz9Sf4Zrl98z4Ubf7LOYDHh72mIgI94RuLEklnYc+MVRuUiqlS
    admin-user: AgBes1M4XlLgyjFJCJ/O4zW5Ea3l6ML45/mlIVZRpNYPBP3tEGYoKmsz2cxkpCT7NR/WZe8IAYy+RAk1lwHdCDA00SznV7Exkfd6vH0xScO1d20f5uO7Oql1QlTq6or06oyRK/1MjyLshU2/URqjzvNnUb+h6JpbfBRlaDTy+hpflszOk42C9rPd2A0XpO0iPopUDF3AK4wmydWYtZNt+IsI5ZyPne47uT82iLau6Ul/ReiQWXVAST4Ry9C653dovWOvMOSyhTk/PSNDGESsXE7TE483WIvCS7WsYpqj1VlUTK0Qg6/vuLm2jy71+KR7cJ8I7Ahwt7SG2k8zo8I7odm88vuY5MEOMZFMfhVH/ywkanh7yUw9hWcBJVszRGIibWBBLVmnL8HFyavcT+1mNMNDejTxtQyzh2YedEJIzdAt7cKNwAf0bqOMjPiU3YMoiIc8l2WjPmVHDuEB/bJ6Evvj7/7K/WiZikxv1+Ka+krv5jzB0S8cUT3z1Wb8M3iuKY7jO9hTi8IEljpqAAuTtMVZFGqIwt2sRzt7ez2BeCQNPM9nQhVhZXtcsLBYDsNzacjuDEUHe9H0bKfXWh+LaedvYumIsM96B3GBUkPhneeIJjPoVvRgecuXedZ7JCbFla1tyieNZUaxaOYGrqMddCVhqKRqbrz55APXMQbGkFfJpaG2ZuWLRBLxJFFda8fvhVKChkG4
