kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgDHMG9z+VeD8LjxO9m/OCtqj6NKxmUIWw6XHlPMegrL0pyYoC1yqYbkuVq593CoL2M7jhySgDctmHoo+kmljhRG+DgyDfRV783QxRHbEqARCQhlSrjYlNi+HFZ76WsYFRnyf5NFHqDM3nqcoTuWSEwX0AqGIuCa1lq5Cz/tu/KoDQkj5yPmiIiBI1XxyufCO04o1SQhRca8C412RBJ0w7YMv5ovWZ5x+l7ZdUOyncCV9Gi5aqvpI4BWJv5Sn/cSWA2PAc7KSTWzIop3JBpEuFv3LepTMzQbjWVLuRnt4OODzGy904P+7TpkFkVWdTpCnkJmCimbwOMNAnW8Rrkutv5LnwY3XvoW0EZ+ENkc85EmF3HRmXcoZGhaBDbAAnWO+WI7Kg8ri7BNuq7M9muUYdhj3dvZq2aayyHW+s2nSdGNx++Kq/9qOpm8G7BOhB3gdWSvyARDB3bWPODxt4hiHeRViJp8RX3DWdk+AKyaMEIPDWRHf1tSjpCC7GaLC2yLSZVQUe6yt5SAhUqOeuewhcNqNGeQYCEbneQmLiY1uett68ZICBLOkK8CCb10EyRC4JexLmEgWdcK5YrEr1bQR3Gb6zMvI/FIb5ea9awQnOzsJko7JrQpdNBuLWg+Cknbh/eojURUS1EaJSwOaSPPdwubebmUmXCfvpqjteqlrskvxfm3+f3u+y8FdjN4avR/OKZ4J02b
    admin-user: AgCjF3wqr/3h1wVR/zWd2SUQKjcSMyijCzAiaoHGloID87sX48z88/xC1BYbHVp6gYQm4m+LUA2n0uy3N+7Ft4UgXABy7mzO+0gtzIuv0itiImYYDF9Ak9ik2PbqjiBxEAhlpNBS2VHa7t+ZM0wO6FEbk5zYR8JLo49cuWW1njguoykIAoHTvmbqnSEkCTlsb4TIo9iNnPICZ/dutrQeJ0yMBTV+dJX1zySKclANV4mjO50woYk2ogZ9tnABOUtgnGH+nQfguDXX/enIqsrMIazaeICLMFIhYYSE/Z+CMHLVMAbsCCakYk1+9cXGSn63pfgrCqO/xUouWNpSOlOlwgM2fkmNxe8BBvlo//y/TzibbXWfzTGL4SYx8wYtoIx9dK4T7cxoS5pMUvem7KyH0797NtSr92D3ao9hpKCBq6AT2cHMnPbcOtMYEYGol7Du90OqJj4t80UIjEXrDJg0G5vWKoVZIMrHjPB6k1R3kMRZLum93Ez3yiIMJe8vXnsoZwtoYUTUk5+TrzUQz9tIY4LjoPpRKWQnu9jMySTxidjXgAprMEN2CyV+nsZYHM+KS29neRfL+QABuwTcUuDqULklCBVaxh9duarSlBs0Q1YKVDwzb7Bq+OxwpRVPzBE83oNTWqcxYq5KiV9tIoUu/GbJFltbpwLxftKF6rzkH/u8LfymqOcpFdjm/1FkTTQ/MmiDfs8rXQ==
