kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCXcFdv40b8SgRc6m/zqr8TaxZusf3ZYimV5TWEZ8sZZ6b90F1O2Me715fbHqe1/eqlLFqLNXjEdfxClb+hQzd3vRoorAIq2T3ZXGqw+5Swzuyx7FzFDy6Ah3wURCEsxqMRKqKmS5kJA1/YisgEHQJp0moB6JpHuwO/J0/CjtreIZJHHoJtX1YXDNLLVjgXdwEXKBieRcyD8LpAUAUFmaDgH+NPceIs0YnrrZUU+N6vbXnb8GQ/VF8EVrzSpwHDESawFWISnKqb3c8JYK82A+yo4jHRLbMbsla3ipq+3nuPIXxWMOavclo3n+SzJlufC2QIqoOlqS8j4bTj12xEWq3VFZSF7pZwVMZ60tnTMAkT1OC3C9kaDtXAu7BwH/tU2meM0SRCnLKULdnwNRG2gTuuHP5+94wq8QfVU1ha8VKmsdPRJGkt0m4qIqwEZjMO223hjXkvy1w/GZS6xOGDcBXrUZ4I5HWaBSyF4NJjRaK5J7xTB55SG6JAjJYja2A8K0YKTViVXNO25ALwWdaosvK1G5kvg4XXPaQ23yRcB0Z2+lXnXla8IVYZ7GWAVJpSnW6I7qMSJtFA1wXKRY4RO8u/NmdhsZceZe8J7iS75VR+OBUzkNQei2ZPHwXPjoS0GfGl5sOSBahrTKzF9yEQXtUuhhVtSTnZX5RmPrsgP1WlMYoybQ+lzqKYZrnpgckyQ6St8AcV
    admin-user: AgCYpKnvxG9LwLWsIxfUQrshn/CfQeg3uJSNq+EEjRk3KXhEcLQJKZbR76a5DNGceaNCVqKBao1qkt98eihGY5L0E4D4CF/lbccN0TzWbidIs4hq+8yWDA5rmpxkuEaFmL8+Hr6dNy1wbjBkiPj3Sc/BOqhb38uOQN3H2L+QMJC1cN1rPIyFTXCIdKPbTL7ra2ycH9fotOw7NOEBeQhkFx0X9e51RbgZuXzIuE4Pha7Y1BZ4MrGgbLxdoSzW0X68bDxqYV/tFmuU0OpJOpr7EP3PL1J3lV1HAQ9mIuL8fvcphWdvDWPFylHVrPL087YHof9gJyXewP2TxpeCZEYRBxgbnKAAelRPIeCTiDdADCnxJaBu4CbbPfr65qbUIioJdWx0Szl7VpWM2/28vl3DEAshWv4+dut23+/TXrisLccww5YGslaE91vSoYX7jBiDyLidvLztg/yPTIVoxdF9wtIyDhOZOzuVEbyeztQ2uqSeDzB78LsUNmgMz3TxhZ1J8O9BkiRz/+rniEYGj/WCnImwmtg/oj4mwjV2nWDnezOIcCObQlRGE2A056WSTUY7+TpHd4xr4Pf6srUviw4PKn1ouW/9FP3rSpwgNGQmpzaueTbVXvyQa3dPZysN8rmj/TeAEMcZ2FiFxiY4QO1tusea2x7+of0w4bFWfcmOPKfF6fBhmIQLIJqTfnUWnWTkkXyi5/np8g==
