kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBkgLo+HoD8qm92/eA7K7z+QRzbhRmrULD49W1tRxJCMPjOul0OKLq/u/fKsMy2FO/B5wl3ihFNAhLsyQJ0zgIvohUbpb0geJkuh0boKkPA5CXgnJl7ME43Th7dUCFT4jMRKdym8VlxeCYFG3szKeayxamFG8Z190LQFp1qqkOYmma0DkMD6Jyk+AM+58QD2ZK/9dbmQwWsQdHea8zKC5SkPvPXLpMgP7Usw2ltDxQqj393j80iHyS/zOuPN1w38cwuw08fkljMtGV5dZf77kNOjxqU8p3UsffgnIYpGH6YA9Mq+CoVBDWwjHahPHaHInYXhj2usU9QGpD7gThBE667Kw6AbQqQRB8XBf8SLUvNgn7pnpLRDUL66197ZeuKeyI8x0yWGPoWT02VP78x1q7vzCNEPNao3RAb6ykQEeSDqwWVxgv84Iq9hipT3/joYgje1CFbMpRNtxnZvipIj0328H0T1hrtyvNE0NGxDYLIUZhqrDlGr4+CovHDKyqLGUpFiGaqzG7MrqfYE8WvMHhpz7LO3GOCHg/dk0W4/3ppaJDVoJiHrGCb9GYTaqYUZlIU/6nMkKekhDe7w8NTN6UezwQsguFbr1P7ipwiYakiT6jt0ltDNF4rkqq10KkEN/mSi5zrXW7UWkyCGJloXYL+mrdoOGyOdUdqXNlINek2ewXZXD/AO+8ih0Tc5Q4TkdEaJZ5A
    admin-user: AgCCRhD6Yn3+TN7H0F/GTDI6m2QL2/dNsOJQPHjwOYo5j2DkkgMJKaZ1XCG79uvXtzEo/99y2zWwiWYOb7D/GNjV39StCl3CaFqLv5eKAH3A6pWdjrrP2hXJ8ym+Tnk5F1RMZush0FOPoZ4h8cJexUTpcVVxC3v94QAHMUCG4197rV429cWRYdOsPgfkz8gm8i6NHya3go9UhthvtEMqCmAJULnHJa5q9TbtlBFkCVSL4Cq7LYLhKdnXM08PEnVQmYwxkjJRITiqtX80E83FrU8GLxKt7/Ll2G2Ojxa6ZxOq2W7aA4GG97Y0Ha2cEHvEI0Q68k8J5UThkgPQ32/vXeaUcTupIAJhc5+qCtL18fjBTVKIqhvsAH27dfmaYcn2EX560UYE907i6383smz0kcxrxaVSyTrZmnq9ZlfVIoikMDBfqcSrfxZbsNT0zmKKhNzbnspyhj8LyzkUy2nixQx+1xDZXF2dzgxoR1XbdekmPhEDsXEwyspDCiHOeQ8cWjMGFxU474kFQ+K95gYroNEKIDO4ev4PGc3dyyfBKIaC1oY6QzMqJduiTAIOEgoyrnY3d7Jj8msaDXhmrCyxlp0kpt3KPUVJ2F/OagmDWLy0KY4q2R7CS4xq4zicP1BARuXpTOccwUZ+Qf758jqz/r0Lk7Xal8cLl0F4wchSVs7j77GROfxu8ynwyJV7VYV1GBhLgZJQBw==
